<?php

declare(strict_types=1);
namespace App\Http\Controllers\Enterprise;
use App\Http\Controllers\Controller;use App\Models\EnterpriseOrganizationMember;use App\Models\User;use App\Nexora\Enterprise\Services\EnterpriseAuditRecorder;use App\Nexora\Enterprise\Services\ScimTokenManager;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Str;
final class ScimController extends Controller
{
    public function __construct(private ScimTokenManager $tokens,private EnterpriseAuditRecorder $audit){}
    public function users(Request $request):JsonResponse{$token=$this->token($request);$members=EnterpriseOrganizationMember::query()->with('user:id,name,email,status')->where('organization_id',$token->organization_id)->where('status','active')->get();$resources=$members->filter(fn($m)=>$m->user)->map(fn($m)=>$this->resource($m->user,$m->role))->values();return response()->json(['schemas'=>['urn:ietf:params:scim:api:messages:2.0:ListResponse'],'totalResults'=>$resources->count(),'startIndex'=>1,'itemsPerPage'=>$resources->count(),'Resources'=>$resources]);}
    public function createUser(Request $request):JsonResponse{$token=$this->token($request);$data=$request->validate(['userName'=>['required','email','max:255'],'active'=>['nullable','boolean'],'name.givenName'=>['nullable','string','max:120'],'name.familyName'=>['nullable','string','max:120']]);$email=strtolower($data['userName']);$name=trim(($data['name']['givenName']??'').' '.($data['name']['familyName']??''))?:$email;$user=User::query()->firstOrCreate(['email'=>$email],['name'=>$name,'password'=>Hash::make(Str::random(64)),'status'=>($data['active']??true)?'active':'suspended','locale'=>'en']);$member=EnterpriseOrganizationMember::query()->updateOrCreate(['organization_id'=>$token->organization_id,'user_id'=>$user->id],['id'=>(string)Str::uuid(),'role'=>'member','status'=>($data['active']??true)?'active':'suspended','joined_at'=>now()]);$this->audit->record('enterprise.scim.user_provisioned',$token->organization_id,null,'user',(string)$user->id,['email'=>$email]);return response()->json($this->resource($user,$member->role),201);}
    public function patchUser(Request $request,int $user):JsonResponse{$token=$this->token($request);$member=EnterpriseOrganizationMember::query()->where('organization_id',$token->organization_id)->where('user_id',$user)->firstOrFail();$target=User::query()->findOrFail($user);$operations=(array)$request->input('Operations',[]);foreach($operations as $operation){$path=strtolower((string)($operation['path']??''));if($path==='active'){$active=(bool)($operation['value']??false);$member->update(['status'=>$active?'active':'suspended']);}}$this->audit->record('enterprise.scim.user_updated',$token->organization_id,null,'user',(string)$target->id);return response()->json($this->resource($target,$member->role));}
    private function token(Request $request){$plain=(string)$request->bearerToken();$record=$plain!==''?$this->tokens->resolve($plain):null;if(!$record)abort(401,'Invalid SCIM bearer token.');return $record;}
    private function resource(User $user,string $role):array{return ['schemas'=>['urn:ietf:params:scim:schemas:core:2.0:User'],'id'=>(string)$user->id,'userName'=>$user->email,'displayName'=>$user->name,'active'=>$user->status==='active','roles'=>[['value'=>$role,'display'=>ucfirst($role)]],'meta'=>['resourceType'=>'User','location'=>url('/scim/v2/Users/'.$user->id)]];}
}
