<?php

declare(strict_types=1);
namespace App\Http\Controllers\Enterprise;
use App\Http\Controllers\Controller;use App\Models\EnterpriseOrganization;use App\Models\EnterpriseOrganizationMember;use App\Models\EnterpriseSsoProvider;use App\Models\User;use App\Nexora\Enterprise\Services\SsoProviderRegistry;use App\Nexora\Security\Session\SessionSecurityManager;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Auth;use Illuminate\Support\Str;
final class SsoController
{
 public function start(Request $request,EnterpriseOrganization $organization,string $provider,SsoProviderRegistry $registry):RedirectResponse{$record=EnterpriseSsoProvider::query()->where('organization_id',$organization->id)->where('slug',$provider)->where('enabled',true)->firstOrFail();$adapter=$registry->get($record->adapter_key);abort_unless($adapter&&$adapter->protocol()===$record->protocol,503,'Identity adapter unavailable.');$state=Str::random(48);$request->session()->put('nexora.enterprise.sso.'.$record->id,['state_hash'=>hash('sha256',$state),'organization_id'=>$organization->id,'expires_at'=>now()->addMinutes(10)->timestamp]);return redirect()->away($adapter->redirectUrl($record,$state));}
 public function callback(Request $request,EnterpriseOrganization $organization,string $provider,SsoProviderRegistry $registry,SessionSecurityManager $sessions):RedirectResponse{$record=EnterpriseSsoProvider::query()->where('organization_id',$organization->id)->where('slug',$provider)->where('enabled',true)->firstOrFail();$saved=(array)$request->session()->pull('nexora.enterprise.sso.'.$record->id,[]);abort_if(!$saved||($saved['expires_at']??0)<time(),419,'SSO state expired.');$state=(string)($request->input('state')??$request->input('RelayState',''));abort_if($state===''||!hash_equals((string)$saved['state_hash'],hash('sha256',$state)),419,'Invalid SSO state.');$adapter=$registry->get($record->adapter_key);abort_unless($adapter,503,'Identity adapter unavailable.');$identity=$adapter->resolveIdentity($record,$request);$user=User::query()->whereRaw('LOWER(email)=?',[strtolower($identity['email'])])->firstOrFail();abort_unless($user->status==='active',403);abort_unless(EnterpriseOrganizationMember::query()->where('organization_id',$organization->id)->where('user_id',$user->id)->where('status','active')->exists(),403);Auth::login($user,false);$sessions->rotateAuthenticatedSession($request);$request->session()->put('nexora.enterprise.organization_id',$organization->id);return redirect('/admin');}
}
