import { useState } from "react";
import { Head, router, useForm } from "@inertiajs/react";
import { AdminLayout } from "@admin/layout/AdminLayout";
import { PageHeader } from "@admin/components/PageHeader";
import { Icon } from "@admin/components/Icon";
import { Badge, Button, ButtonLink, Card, Modal, Select } from "@nexora/admin-ui";

type Revision = { id:number; revision:number; title:string; excerpt:string|null; document_status:string|null; workflow_status:string|null; creator:string|null; created_at:string|null; content?: { version:number; blocks:Array<Record<string, unknown>> }; metadata?: Record<string, unknown> };
type Diff = { from:number; to:number; fields:Array<{field:string;before:string|null;after:string|null;changed:boolean}>; blocks:Array<{id:string;change:"added"|"removed"|"changed";before:Record<string,unknown>|null;after:Record<string,unknown>|null}>; summary:{added:number;removed:number;changed:number} };
const time = (value:string|null) => value ? new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)) : "Unknown time";
const blockText = (block:Record<string,unknown>|null) => { if(!block)return "—"; const data = typeof block.data === "object" && block.data ? block.data as Record<string,unknown> : {}; if(Array.isArray(data.items)) return data.items.join(" · "); return String(data.text ?? data.code ?? block.type ?? "Block"); };

export default function Revisions({ document, revisions, selected, compare }: { document:{id:number;title:string;lock_version:number}; revisions:Revision[]; selected:Revision|null; compare:{revision:Revision;diff:Diff}|null }) {
    const [restoreOpen,setRestoreOpen]=useState(false);
    const restoreForm=useForm({lock_version:document.lock_version});
    const selectRevision=(id:string)=>router.get(`/admin/documents/${document.id}/revisions`,{revision:id},{preserveState:true,preserveScroll:true});
    const selectCompare=(id:string)=>router.get(`/admin/documents/${document.id}/revisions`,{revision:selected?.id ?? "",compare:id},{preserveState:true,preserveScroll:true});
    const summary=compare?.diff.summary;
    return <AdminLayout>
        <Head title={`Revisions · ${document.title}`} />
        <PageHeader eyebrow="Nexora Editorial" title="Revision history" description="Compare immutable snapshots, understand structural changes and restore an earlier state without deleting newer history." actions={<ButtonLink href={`/admin/documents/${document.id}/edit`} variant="secondary" leadingIcon={<Icon name="left" className="h-4 w-4" />}>Back to writer</ButtonLink>} />
        {revisions.length===0 ? <Card className="p-10 text-center text-sm text-[var(--nx-text-muted)]">No revision snapshots exist yet.</Card> : <div className="grid gap-5 xl:grid-cols-[20rem_minmax(0,1fr)]">
            <Card className="h-fit p-4 xl:sticky xl:top-[calc(var(--nx-header-height)+2rem)]"><div className="mb-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[var(--nx-text-muted)]">Timeline</p><p className="mt-1 text-sm text-[var(--nx-text-secondary)]">{revisions.length} immutable snapshots</p></div><div className="grid gap-2">{revisions.map((revision)=><Button key={revision.id} type="button" variant={selected?.id===revision.id?"primary":"ghost"} className="h-auto w-full justify-start px-3 py-3 text-start" onClick={()=>selectRevision(String(revision.id))}><span className="grid min-w-0 flex-1 gap-0.5"><span>Revision {revision.revision}</span><span className="truncate text-xs font-normal opacity-75">{revision.creator ?? "System"} · {time(revision.created_at)}</span></span></Button>)}</div></Card>
            <div className="grid gap-5">
                <Card className="p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Badge tone="brand">Revision {selected?.revision}</Badge>{selected?.workflow_status && <Badge>{selected.workflow_status.replaceAll("_"," ")}</Badge>}</div><h2 className="mt-3 text-xl font-semibold text-[var(--nx-text)]">{selected?.title}</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">Saved by {selected?.creator ?? "System"} · {time(selected?.created_at ?? null)}</p></div><div className="flex flex-wrap gap-2"><Select ariaLabel="Compare against revision" className="w-56" value={compare?.revision.id ? String(compare.revision.id) : ""} onChange={selectCompare} options={revisions.filter((item)=>item.id!==selected?.id).map((item)=>({value:String(item.id),label:`Revision ${item.revision}`,description:time(item.created_at)}))} /><Button type="button" variant="secondary" onClick={()=>setRestoreOpen(true)} leadingIcon={<Icon name="refresh" className="h-4 w-4" />}>Restore this revision</Button></div></div></Card>
                {compare ? <><div className="grid gap-4 sm:grid-cols-3"><Card className="p-4"><p className="text-xs text-[var(--nx-text-muted)]">Blocks added</p><p className="mt-1 text-2xl font-semibold text-emerald-600">{summary?.added ?? 0}</p></Card><Card className="p-4"><p className="text-xs text-[var(--nx-text-muted)]">Blocks changed</p><p className="mt-1 text-2xl font-semibold text-amber-600">{summary?.changed ?? 0}</p></Card><Card className="p-4"><p className="text-xs text-[var(--nx-text-muted)]">Blocks removed</p><p className="mt-1 text-2xl font-semibold text-red-600">{summary?.removed ?? 0}</p></Card></div>
                    <Card className="p-5 sm:p-6"><h2 className="text-base font-semibold text-[var(--nx-text)]">Field changes</h2><div className="mt-4 grid gap-3">{compare.diff.fields.filter((field)=>field.changed).length===0?<p className="text-sm text-[var(--nx-text-muted)]">No title, excerpt or state changes between these revisions.</p>:compare.diff.fields.filter((field)=>field.changed).map((field)=><div key={field.field} className="grid gap-3 rounded-xl border border-[var(--nx-border)] bg-[var(--nx-surface-subtle)] p-4 lg:grid-cols-[9rem_1fr_1fr]"><p className="text-xs font-semibold text-[var(--nx-text)]">{field.field}</p><div><p className="text-[11px] uppercase tracking-wide text-red-500">Before</p><p className="mt-1 whitespace-pre-wrap text-sm text-[var(--nx-text-secondary)]">{field.before || "—"}</p></div><div><p className="text-[11px] uppercase tracking-wide text-emerald-600">After</p><p className="mt-1 whitespace-pre-wrap text-sm text-[var(--nx-text-secondary)]">{field.after || "—"}</p></div></div>)}</div></Card>
                    <Card className="p-5 sm:p-6"><h2 className="text-base font-semibold text-[var(--nx-text)]">Block changes</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">Semantic comparison follows stable block IDs rather than raw HTML lines.</p><div className="mt-4 grid gap-3">{compare.diff.blocks.length===0?<p className="text-sm text-[var(--nx-text-muted)]">No block changes between these revisions.</p>:compare.diff.blocks.map((block)=><div key={`${block.id}-${block.change}`} className="rounded-xl border border-[var(--nx-border)] p-4"><Badge tone={block.change==="added"?"success":block.change==="removed"?"danger":"warning"}>{block.change}</Badge><div className="mt-3 grid gap-3 lg:grid-cols-2"><div className="rounded-lg bg-red-50 p-3 text-sm text-red-800 dark:bg-red-950/25 dark:text-red-300">{blockText(block.before)}</div><div className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800 dark:bg-emerald-950/25 dark:text-emerald-300">{blockText(block.after)}</div></div></div>)}</div></Card></> : <Card className="p-8 text-center"><Icon name="history" className="mx-auto h-8 w-8 text-[var(--nx-text-muted)]" /><p className="mt-3 text-sm text-[var(--nx-text-muted)]">Choose another revision to compare with this snapshot.</p></Card>}
            </div>
        </div>}
        <Modal open={restoreOpen} onClose={()=>setRestoreOpen(false)} title={`Restore revision ${selected?.revision ?? ""}?`} description="Nexora will not delete current history. The selected snapshot becomes the document state and a brand-new revision is appended." footer={<><Button type="button" variant="secondary" onClick={()=>setRestoreOpen(false)}>Cancel</Button><Button type="button" loading={restoreForm.processing} onClick={()=>selected&&restoreForm.post(`/admin/documents/${document.id}/revisions/${selected.id}/restore`)} leadingIcon={<Icon name="refresh" className="h-4 w-4" />}>Restore as new revision</Button></>} />
    </AdminLayout>;
}
