import { useMemo, useState } from "react";
import { Head, router, useForm } from "@inertiajs/react";
import { AdminLayout } from "@admin/layout/AdminLayout";
import { PageHeader } from "@admin/components/PageHeader";
import { Icon } from "@admin/components/Icon";
import { ConfirmDialog } from "@admin/components/ConfirmDialog";
import { DataTable, type Column } from "@admin/components/data/DataTable";
import { Badge, Button, ButtonLink, Card, Checkbox } from "@nexora/admin-ui";

type Version={id:string;version:string;state:string;runtime_mode:string;migration_policy:string;schema_compatible_rollback:boolean;compatibility_status:string;trust_tier:string|null;signature_status:string|null;installed_at:string|null;dependencies:{identifier:string;constraint:string;optional:boolean}[]};
type Capability={slug:string;name:string;group:string;risk:string;description:string;registered:boolean;granted:boolean}; type Event={id:string;event:string;status:string;context:Record<string,unknown>;created_at:string|null};
type Props={extension:{id:string;identifier:string;name:string;type:string;status:string;current_version:string|null;description:string|null;publisher:string|null;trust_tier:string|null};versions:Version[];capabilities:Capability[];events:Event[];canManage:boolean};
const human=(v:string)=>v.replace(/[._-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function ExtensionShow({extension,versions,capabilities,events,canManage}:Props){
 const [uninstallOpen,setUninstallOpen]=useState(false); const [uninstalling,setUninstalling]=useState(false);
 const grants=useForm({capabilities:capabilities.filter(c=>c.granted).map(c=>c.slug)}); const toggle=(slug:string)=>grants.setData('capabilities',grants.data.capabilities.includes(slug)?grants.data.capabilities.filter(v=>v!==slug):[...grants.data.capabilities,slug]);
 const columns=useMemo<Column<Version>[]>(()=>[
  {key:'version',label:'Version',render:v=><div><p className="font-semibold text-[var(--nx-text)]">v{v.version}</p><p className="text-xs text-[var(--nx-text-muted)]">{human(v.runtime_mode)}</p></div>},
  {key:'state',label:'State',render:v=><Badge tone={v.state==='active'?'success':'neutral'}>{human(v.state)}</Badge>},
  {key:'trust',label:'Trust',render:v=><div className="text-sm text-[var(--nx-text-secondary)]">{human(v.trust_tier??'unknown')}<div className="text-xs text-[var(--nx-text-muted)]">Signature: {human(v.signature_status??'unknown')}</div></div>},
  {key:'migration',label:'Schema policy',render:v=><div className="text-sm text-[var(--nx-text-secondary)]">{human(v.migration_policy)}<div className="text-xs text-[var(--nx-text-muted)]">{v.schema_compatible_rollback?'Rollback declared compatible':'Rollback guarded'}</div></div>},
  {key:'dependencies',label:'Dependencies',render:v=><span className="text-sm text-[var(--nx-text-secondary)]">{v.dependencies.length?v.dependencies.map(d=>`${d.identifier} ${d.constraint}`).join(', '):'None'}</span>},
  {key:'actions',label:'',className:'w-24',render:v=>canManage&&v.state!=='active'?<Button size="sm" variant="secondary" onClick={()=>router.post(`/admin/extensions/${extension.id}/enable`,{version:v.version},{preserveScroll:true})}>Activate</Button>:null},
 ],[canManage,extension.id]);
 const uninstall=()=>{setUninstalling(true);router.delete(`/admin/extensions/${extension.id}`,{preserveScroll:true,onFinish:()=>{setUninstalling(false);setUninstallOpen(false)}})};
 return <AdminLayout><Head title={extension.name}/><PageHeader eyebrow="Extension lifecycle" title={extension.name} description={extension.description??extension.identifier} actions={<ButtonLink href="/admin/extensions" variant="secondary">Back to Extensions</ButtonLink>}/>
 <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card className="p-4"><p className="text-xs text-[var(--nx-text-muted)]">Status</p><div className="mt-2"><Badge tone={extension.status==='enabled'?'success':'warning'}>{human(extension.status)}</Badge></div></Card><Card className="p-4"><p className="text-xs text-[var(--nx-text-muted)]">Active version</p><p className="mt-2 font-semibold text-[var(--nx-text)]">{extension.current_version??'Not enabled'}</p></Card><Card className="p-4"><p className="text-xs text-[var(--nx-text-muted)]">Publisher</p><p className="mt-2 font-semibold text-[var(--nx-text)]">{extension.publisher??'Unknown'}</p></Card><Card className="p-4"><p className="text-xs text-[var(--nx-text-muted)]">Package type</p><p className="mt-2 font-semibold text-[var(--nx-text)]">{human(extension.type)}</p></Card></div>
 <div className="mb-5 flex flex-wrap gap-2">{canManage&&extension.status==='enabled'&&<Button variant="secondary" onClick={()=>router.post(`/admin/extensions/${extension.id}/disable`,{}, {preserveScroll:true})}>Disable</Button>}{canManage&&extension.status!=='enabled'&&<Button onClick={()=>router.post(`/admin/extensions/${extension.id}/enable`,{}, {preserveScroll:true})}>Enable current version</Button>}{canManage&&versions.length>1&&<Button variant="secondary" onClick={()=>router.post(`/admin/extensions/${extension.id}/rollback`,{}, {preserveScroll:true})}>Rollback</Button>}{canManage&&<Button variant="danger" onClick={()=>setUninstallOpen(true)}>Uninstall</Button>}</div>
 <DataTable rows={versions} columns={columns}/>
 <div className="mt-5 grid gap-5 xl:grid-cols-2"><Card className="p-5 sm:p-6"><div className="mb-4"><h2 className="font-semibold text-[var(--nx-text)]">Requested capabilities</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">Capabilities are denied until explicitly granted. Enabling is blocked while required grants are missing.</p></div><div className="grid gap-3">{capabilities.length===0?<p className="text-sm text-[var(--nx-text-muted)]">This extension requests no runtime capabilities.</p>:capabilities.map(c=><Checkbox key={c.slug} checked={grants.data.capabilities.includes(c.slug)} disabled={!canManage || !c.registered} onChange={()=>toggle(c.slug)} label={c.name} description={`${c.registered ? human(c.risk)+" risk" : "Unavailable capability"} · ${c.description}`}/>)}</div>{canManage&&capabilities.length>0&&<Button className="mt-4" loading={grants.processing} leadingIcon={<Icon name="shield" className="h-4 w-4"/>} onClick={()=>grants.put(`/admin/extensions/${extension.id}/capabilities`,{preserveScroll:true})}>Save capability grants</Button>}</Card>
 <Card className="p-5 sm:p-6"><h2 className="font-semibold text-[var(--nx-text)]">Lifecycle history</h2><div className="mt-4 grid gap-3">{events.length===0?<p className="text-sm text-[var(--nx-text-muted)]">No lifecycle events recorded.</p>:events.map(e=><div key={e.id} className="rounded-xl border border-[var(--nx-border)] p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-[var(--nx-text)]">{human(e.event)}</p><Badge>{human(e.status)}</Badge></div>{e.created_at&&<p className="mt-1 text-xs text-[var(--nx-text-muted)]">{new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(e.created_at))}</p>}</div>)}</div></Card></div>
 <ConfirmDialog open={uninstallOpen} title={`Uninstall ${extension.name}?`} description="Installed extension files will be removed. Lifecycle history stays recorded, and uninstall is blocked if enabled extensions depend on this package." confirmLabel="Uninstall extension" processing={uninstalling} onCancel={()=>setUninstallOpen(false)} onConfirm={uninstall}/>
 </AdminLayout>;
}
