import { Head } from "@inertiajs/react";
import { AdminLayout } from "@admin/layout/AdminLayout";
import { PageHeader } from "@admin/components/PageHeader";
import { Icon } from "@admin/components/Icon";
import { Badge, Card, ButtonLink } from "@nexora/admin-ui";
import { CrmNav } from "./_CrmNav";
type Props={summary:{organizations:number;contacts:number;open_leads:number;open_opportunities:number;won_opportunities:number;pipeline_value:string;currency:string};recentOpportunities:Array<{id:string;name:string;status:string;stage:string|null;organization:string|null;contact:string|null;amount:string;updated_at:string|null}>;recentActivities:Array<{id:string;type:string;title:string;subject_type:string;subject_id:string;occurred_at:string|null}>};
const human=(v:string)=>v.replace(/[_-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function CrmIndex({summary,recentOpportunities,recentActivities}:Props){
 const stats=[["Organizations",summary.organizations,"building-2"],["Contacts",summary.contacts,"contact"],["Open leads",summary.open_leads,"user-plus"],["Open opportunities",summary.open_opportunities,"target"],["Won opportunities",summary.won_opportunities,"trophy"],[`Pipeline value (${summary.currency})`,summary.pipeline_value,"wallet"]] as const;
 return <AdminLayout><Head title="CRM"/><PageHeader eyebrow="Customer relationships" title="CRM" description="Organizations, contacts, leads, opportunities and relationship activity remain provider-neutral and extension-safe."/>
 <CrmNav current="/admin/crm"/>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{stats.map(([label,value,icon])=><Card key={label} className="p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--nx-brand-soft)] text-[var(--nx-brand-600)]"><Icon name={icon} className="h-4 w-4"/></span><div><p className="text-xs text-[var(--nx-text-muted)]">{label}</p><p className="mt-1 text-xl font-semibold text-[var(--nx-text)]">{value}</p></div></div></Card>)}</div>
 <div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Card className="p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-[var(--nx-text)]">Recent opportunities</h2><ButtonLink href="/admin/crm/opportunities" size="sm" variant="secondary">View pipeline</ButtonLink></div><div className="mt-4 grid gap-2">{recentOpportunities.length===0?<p className="py-8 text-center text-sm text-[var(--nx-text-muted)]">No opportunities yet.</p>:recentOpportunities.map(o=><div key={o.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[var(--nx-border)] p-3"><div><ButtonLink href={`/admin/crm/opportunities/${o.id}`} variant="ghost" size="sm" className="h-auto p-0 font-semibold">{o.name}</ButtonLink><p className="mt-1 text-xs text-[var(--nx-text-muted)]">{o.organization??o.contact??"Unlinked relationship"} · {o.stage??"No stage"}</p></div><div className="flex items-center gap-3"><Badge>{human(o.status)}</Badge><span className="text-sm font-semibold text-[var(--nx-text)]">{o.amount}</span></div></div>)}</div></Card>
 <Card className="p-5 sm:p-6"><h2 className="font-semibold text-[var(--nx-text)]">Recent relationship activity</h2><div className="mt-4 grid gap-2">{recentActivities.length===0?<p className="py-8 text-center text-sm text-[var(--nx-text-muted)]">No activities yet.</p>:recentActivities.map(a=><div key={a.id} className="rounded-xl border border-[var(--nx-border)] p-3"><div className="flex items-center gap-2"><Badge>{human(a.type)}</Badge><p className="font-medium text-[var(--nx-text)]">{a.title}</p></div><p className="mt-1 text-xs text-[var(--nx-text-muted)]">{human(a.subject_type)}</p></div>)}</div></Card></div>
 </AdminLayout>;
}
