import { useMemo,useState } from "react";
import { Head,router,useForm } from "@inertiajs/react";
import { AdminLayout } from "@admin/layout/AdminLayout"; import { PageHeader } from "@admin/components/PageHeader"; import { DataTable,type Column,type Paginator } from "@admin/components/data/DataTable"; import { EmptyState } from "@admin/components/LoadingStates";
import { Button,ButtonLink,Input,Modal,Select,Textarea } from "@nexora/admin-ui"; import { CrmNav } from "./_CrmNav";
type Owner={id:number;name:string}; type Row={id:string;name:string;domain:string|null;industry:string|null;lifecycle_stage:string;owner:string|null;contacts_count:number;opportunities_count:number;commerce_links_count:number;created_at:string|null};
type Props={organizations:Paginator<Row>;filters:{q:string};owners:Owner[];canManage:boolean}; const human=(v:string)=>v.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function Organizations({organizations,filters,owners,canManage}:Props){const[open,setOpen]=useState(false);const[search,setSearch]=useState(filters.q);const form=useForm({name:"",domain:"",website:"",industry:"",email:"",phone:"",lifecycle_stage:"prospect",owner_id:"",description:""});
 const columns=useMemo<Column<Row>[]>(()=>[
  {key:"organization",label:"Organization",render:r=><div><ButtonLink href={`/admin/crm/organizations/${r.id}`} variant="ghost" size="sm" className="h-auto p-0 font-semibold">{r.name}</ButtonLink><p className="mt-1 text-xs text-[var(--nx-text-muted)]">{r.domain??"No domain"}</p></div>},
  {key:"industry",label:"Industry",render:r=><span className="text-sm text-[var(--nx-text-secondary)]">{r.industry??"—"}</span>},{key:"stage",label:"Lifecycle",render:r=><span className="text-sm text-[var(--nx-text-secondary)]">{human(r.lifecycle_stage)}</span>},
  {key:"owner",label:"Owner",render:r=><span className="text-sm text-[var(--nx-text-secondary)]">{r.owner??"Unassigned"}</span>},{key:"relationships",label:"Relationships",render:r=><span className="text-sm text-[var(--nx-text-secondary)]">{r.contacts_count} contacts · {r.opportunities_count} opportunities</span>},
 ],[]);
 const submit=()=>form.post('/admin/crm/organizations',{preserveScroll:true,onSuccess:()=>{form.reset();setOpen(false)}});
 return <AdminLayout><Head title="CRM Organizations"/><PageHeader eyebrow="CRM" title="Organizations" description="Companies and organizations stay separate from billing identities and can own contacts, leads and opportunities." actions={canManage?<Button onClick={()=>setOpen(true)}>Create organization</Button>:undefined}/><CrmNav current="/admin/crm/organizations"/>
 <DataTable rows={organizations.data} columns={columns} paginator={organizations} toolbar={<div className="flex flex-wrap gap-2"><Input aria-label="Search organizations" placeholder="Search organizations" value={search} onChange={e=>setSearch(e.target.value)}/><Button variant="secondary" onClick={()=>router.get('/admin/crm/organizations',search?{q:search}:{},{preserveState:true,preserveScroll:true})}>Search</Button></div>} empty={<EmptyState title="No organizations" description="Create the first company or organization relationship record."/>}/>
 <Modal open={open} onClose={()=>setOpen(false)} title="Create organization" footer={<><Button variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={form.processing} onClick={submit}>Create organization</Button></>}><div className="grid gap-4 sm:grid-cols-2"><Input label="Organization name" value={form.data.name} onChange={e=>form.setData('name',e.target.value)} error={form.errors.name}/><Input label="Domain" value={form.data.domain} onChange={e=>form.setData('domain',e.target.value)} placeholder="example.com"/><Input label="Website" value={form.data.website} onChange={e=>form.setData('website',e.target.value)}/><Input label="Industry" value={form.data.industry} onChange={e=>form.setData('industry',e.target.value)}/><Input label="Email" value={form.data.email} onChange={e=>form.setData('email',e.target.value)}/><Input label="Phone" value={form.data.phone} onChange={e=>form.setData('phone',e.target.value)}/><Select label="Lifecycle stage" value={form.data.lifecycle_stage} onChange={v=>form.setData('lifecycle_stage',v)} options={['prospect','customer','partner','inactive'].map(v=>({value:v,label:human(v)}))}/><Select label="Owner" value={form.data.owner_id} onChange={v=>form.setData('owner_id',v)} options={[{value:'',label:'Unassigned'},...owners.map(o=>({value:String(o.id),label:o.name}))]}/><Textarea className="sm:col-span-2" label="Description" value={form.data.description} onChange={e=>form.setData('description',e.target.value)}/></div></Modal>
 </AdminLayout>}
