import type { SVGProps } from "react";
import {
    Activity, AlertTriangle, Bell, Blocks, BookOpenText, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, ChevronUp,
    Circle, CircleDashed, Clock3, Code2, Command, Database, Download, Edit3, FileArchive, FileAudio, FileText, FileVideo, FolderCheck,
    Gauge, Globe2, GripVertical, HardDrive, Heading2, Home, Image, Info, KeyRound, List, LoaderCircle, LockKeyhole, LogOut, Mail, Menu, Monitor,
    LayoutTemplate, Rows3, Columns3, MousePointerClick, Minus, Smartphone, Tablet, Undo2, Redo2, Layers3, Component, Save, Copy, Maximize2,
    Moon, Newspaper, PackageCheck, PackageOpen, Palette, Eye, RotateCcw, ExternalLink, PanelLeftClose, PanelLeftOpen, Pilcrow, Plus, Quote, RefreshCw, Search, Send, Settings, ShieldCheck,
    ShieldPlus, Sun, Cloud, Zap, TerminalSquare, Trash2, User, Users, X, XCircle, ShoppingCart, Wallet, BadgeCheck, LifeBuoy, UserCheck, CreditCard, Inbox, Clock, TriangleAlert, UserX, TimerOff, CircleAlert,
    type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
    home: Home,
    users: Users,
    settings: Settings,
    activity: Activity,
    shield: ShieldCheck,
    history: Clock3,
    bell: Bell,
    user: User,
    plus: Plus,
    edit: Edit3,
    trash: Trash2,
    lock: LockKeyhole,
    command: Command,
    menu: Menu,
    close: X,
    search: Search,
    logout: LogOut,
    sun: Sun,
    moon: Moon,
    monitor: Monitor,
    check: Check,
    alert: AlertTriangle,
    blocks: Blocks,
    key: KeyRound,
    refresh: RefreshCw,
    sentinel: ShieldPlus,
    success: CheckCircle2,
    error: XCircle,
    pending: Circle,
    loading: LoaderCircle,
    info: Info,
    database: Database,
    terminal: TerminalSquare,
    package: PackageOpen,
    "package-check": PackageCheck,
    "file-text": FileText,
    download: Download,
    archive: FileArchive,
    folder: FolderCheck,
    drive: HardDrive,
    gauge: Gauge,
    globe: Globe2,
    cloud: Cloud,
    zap: Zap,
    left: ChevronLeft,
    right: ChevronRight,
    up: ChevronUp,
    down: ChevronDown,
    dashed: CircleDashed,
    "panel-close": PanelLeftClose,
    "panel-open": PanelLeftOpen,
    paragraph: Pilcrow,
    heading: Heading2,
    list: List,
    quote: Quote,
    code: Code2,
    grip: GripVertical,
    writer: BookOpenText,
    newspaper: Newspaper,
    palette: Palette,
    eye: Eye,
    rollback: RotateCcw,
    external: ExternalLink,
    studio: LayoutTemplate,
    section: LayoutTemplate,
    stack: Rows3,
    grid: Columns3,
    button: MousePointerClick,
    divider: Minus,
    spacer: Maximize2,
    mobile: Smartphone,
    tablet: Tablet,
    undo: Undo2,
    redo: Redo2,
    layers: Layers3,
    component: Component,
    save: Save,
    copy: Copy,
    image: Image,
    send: Send,
    mail: Mail,
    video: FileVideo,
    audio: FileAudio,
    "shopping-cart": ShoppingCart,
    wallet: Wallet,
    "badge-check": BadgeCheck,
    "life-buoy": LifeBuoy,
    "user-check": UserCheck,
    "credit-card": CreditCard,
    inbox: Inbox,
    clock: Clock,
    "triangle-alert": TriangleAlert,
    "user-x": UserX,
    "timer-off": TimerOff,
    "circle-alert": CircleAlert,
};

export function Icon({ name, ...props }: SVGProps<SVGSVGElement> & { name: string }) {
    const Component = icons[name] ?? Activity;
    return <Component aria-hidden="true" strokeWidth={1.8} {...props} />;
}
