import { Head } from "@inertiajs/react";
import { AdminLayout } from "@admin/layout/AdminLayout";
import { PageHeader } from "@admin/components/PageHeader";
import { Icon } from "@admin/components/Icon";
import { Badge, ButtonLink, Card } from "@nexora/admin-ui";
import { MembershipNav } from "./_MembershipNav";
type Props={summary:{plans:number;active_plans:number;members:number;active_members:number;protected_resources:number;commerce_linked:number};recent:Array<{id:string;plan:string|null;member:string;status:string;ends_at:string|null;created_at:string|null}>};
const human=(v:string)=>v.replace(/[_-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function MembershipIndex({summary,recent}:Props){const stats=[['Plans',summary.plans,'badge-check'],['Active plans',summary.active_plans,'circle-check'],['Memberships',summary.members,'users'],['Active members',summary.active_members,'user-check'],['Protected resources',summary.protected_resources,'shield-check'],['Commerce linked',summary.commerce_linked,'credit-card']] as const;return <AdminLayout><Head title="Membership"/><PageHeader eyebrow="Access & entitlements" title="Membership" description="Plans, entitlements and protected-content access remain separate from Commerce billing identities and external LMS packages."/><MembershipNav current="/admin/membership"/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{stats.map(([label,value,icon])=><Card key={label} className="p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--nx-brand-soft)] text-[var(--nx-brand-600)]"><Icon name={icon} className="h-4 w-4"/></span><div><p className="text-xs text-[var(--nx-text-muted)]">{label}</p><p className="mt-1 text-xl font-semibold text-[var(--nx-text)]">{value}</p></div></div></Card>)}</div><Card className="mt-5 p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-[var(--nx-text)]">Recent memberships</h2><ButtonLink href="/admin/membership/members" size="sm" variant="secondary">View members</ButtonLink></div><div className="mt-4 grid gap-2">{recent.length===0?<p className="py-8 text-center text-sm text-[var(--nx-text-muted)]">No memberships yet.</p>:recent.map(m=><div key={m.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[var(--nx-border)] p-3"><div><p className="font-medium text-[var(--nx-text)]">{m.member}</p><p className="mt-1 text-xs text-[var(--nx-text-muted)]">{m.plan??'Unknown plan'}{m.ends_at?` · Ends ${new Date(m.ends_at).toLocaleDateString()}`:''}</p></div><Badge>{human(m.status)}</Badge></div>)}</div></Card></AdminLayout>}
