import type { FormEvent } from "react";
import { Head, useForm } from "@inertiajs/react";
import { AdminLayout } from "@admin/layout/AdminLayout";
import { PageHeader } from "@admin/components/PageHeader";
import { Button, ButtonLink, Card, Checkbox, Input, Select } from "@nexora/admin-ui";

type Role={id:number;name:string;slug:string};
type Locale={code:string;label:string;flag?:string;flagUrl?:string};
type User={id:number;name:string;email:string;status:string;timezone:string;locale:string;verified:boolean;roleIds:number[]};

export default function UserForm({user,roles,locales}:{user:User|null;roles:Role[];locales:Locale[]}){
 const editing=!!user;
 const {data,setData,post,put,processing,errors}=useForm({name:user?.name??"",email:user?.email??"",status:user?.status??"active",timezone:user?.timezone??"UTC",locale:user?.locale??"en",verified:user?.verified??false,roles:user?.roleIds??[] as number[],password:"",password_confirmation:""});
 const submit=(e:FormEvent)=>{e.preventDefault();editing?put(`/admin/users/${user.id}`):post("/admin/users")};
 const toggle=(id:number)=>setData("roles",data.roles.includes(id)?data.roles.filter(v=>v!==id):[...data.roles,id]);
 return <AdminLayout><Head title={editing?"Edit user":"Create user"}/><PageHeader eyebrow="Identity" title={editing?"Edit user":"Create user"} description="Keep identity, access and security details explicit. Role changes take effect immediately." actions={<ButtonLink href="/admin/users" variant="secondary">Back</ButtonLink>}/><form onSubmit={submit} className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><Card className="p-5 sm:p-6"><div className="grid gap-5 sm:grid-cols-2"><Input label="Full name" value={data.name} onChange={e=>setData("name",e.target.value)} error={errors.name}/><Input label="Email" type="email" value={data.email} onChange={e=>setData("email",e.target.value)} error={errors.email}/><Select label="Status" value={data.status} onChange={value=>setData("status",value)} options={[{value:"active",label:"Active"},{value:"suspended",label:"Suspended"}]}/><Input label="Timezone" value={data.timezone} onChange={e=>setData("timezone",e.target.value)} error={errors.timezone} hint="IANA timezone, e.g. Asia/Karachi"/><Select label="Language" value={data.locale} onChange={value=>setData("locale",value)} error={errors.locale} options={locales.map(locale=>({value:locale.code,label:locale.label,leading:locale.flagUrl?<img src={locale.flagUrl} alt="" className="h-4 w-6 rounded-[3px] object-cover ring-1 ring-black/5"/>:locale.flag?<span className="text-base">{locale.flag}</span>:undefined}))}/><div className="flex items-end pb-2"><Checkbox label="Email verified" checked={data.verified} onChange={e=>setData("verified",e.target.checked)}/></div><Input label={editing?"New password (optional)":"Password"} type="password" value={data.password} onChange={e=>setData("password",e.target.value)} error={errors.password}/><Input label="Confirm password" type="password" value={data.password_confirmation} onChange={e=>setData("password_confirmation",e.target.value)}/></div></Card><div className="grid content-start gap-5"><Card className="p-5"><h2 className="text-sm font-semibold text-[var(--nx-text)]">Roles</h2><div className="mt-4 grid gap-3">{roles.map(r=><Checkbox key={r.id} checked={data.roles.includes(r.id)} onChange={()=>toggle(r.id)} label={r.name} description={r.slug}/>)}</div></Card><div className="flex justify-end gap-2"><ButtonLink href="/admin/users" variant="secondary">Cancel</ButtonLink><Button type="submit" loading={processing}>{editing?"Save changes":"Create user"}</Button></div></div></form></AdminLayout>
}
