import { FormEvent, useState } from "react";
import { Head, router } from "@inertiajs/react";
import { AdminLayout } from "@admin/layout/AdminLayout";
import { PageHeader } from "@admin/components/PageHeader";
import { EmptyState } from "@admin/components/LoadingStates";
import { DataTable, type Column, type Paginator } from "@admin/components/data/DataTable";
import { Icon } from "@admin/components/Icon";
import { SavedViews } from "@admin/components/data/SavedViews";
import { ConfirmDialog } from "@admin/components/ConfirmDialog";
import { ColumnControls } from "@admin/components/data/ColumnControls";
import { Badge, Button, ButtonLink, IconButton, IconLink, Input, Select } from "@nexora/admin-ui";
type Role={name:string;slug:string}; type UserRow={id:number;name:string;email:string;status:string;verified:boolean;roles:Role[];lastLoginAt:string|null;createdAt:string|null};
export default function UsersIndex({users,filters,can}:{users:Paginator<UserRow>;filters:{search:string;status:string;sort:string;direction:"asc"|"desc"};can:{create:boolean;update:boolean;delete:boolean}}){
 const [search,setSearch]=useState(filters.search),[status,setStatus]=useState(filters.status),[selected,setSelected]=useState<Array<number|string>>([]),[deleteTarget,setDeleteTarget]=useState<UserRow|null>(null),[deleting,setDeleting]=useState(false),[loading,setLoading]=useState(false),[bulkAction,setBulkAction]=useState(""),[sort,setSort]=useState(filters.sort),[direction,setDirection]=useState<"asc"|"desc">(filters.direction),[visibleColumns,setVisibleColumns]=useState(["user","roles","status","login","actions"]);
 function submit(e:FormEvent){e.preventDefault();setLoading(true);router.get("/admin/users",{search:search||undefined,status:status||undefined,sort:sort||undefined,direction:sort?direction:undefined},{preserveState:true,preserveScroll:true,replace:true,onFinish:()=>setLoading(false)})}
 const allColumns:Column<UserRow>[]=[
  {key:"user",label:"User",sortKey:"name",render:u=><div><div className="font-semibold text-[var(--nx-text)]">{u.name}</div><div className="mt-1 text-xs text-[var(--nx-text-muted)]">{u.email}</div></div>},
  {key:"roles",label:"Roles",render:u=><div className="flex flex-wrap gap-1.5">{u.roles.length?u.roles.map(r=><Badge key={r.slug}>{r.name}</Badge>):<span className="text-sm text-[var(--nx-text-muted)]">No role</span>}</div>},
  {key:"status",label:"Status",sortKey:"status",render:u=><div className="flex gap-1.5"><Badge tone={u.status==="active"?"success":"danger"}>{u.status}</Badge><Badge tone={u.verified?"neutral":"warning"}>{u.verified?"Verified":"Pending"}</Badge></div>},
  {key:"login",label:"Last login",sortKey:"last_login_at",render:u=><span className="text-sm text-[var(--nx-text-secondary)]">{u.lastLoginAt?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(u.lastLoginAt)):"Never"}</span>},
  {key:"actions",label:"",className:"text-right",render:u=><div className="flex justify-end gap-1">{can.update&&<IconLink href={`/admin/users/${u.id}/edit`} label={`Edit ${u.name}`}><Icon name="edit" className="h-4 w-4"/></IconLink>}{can.delete&&<IconButton label={`Delete ${u.name}`} tone="danger" onClick={()=>setDeleteTarget(u)}><Icon name="trash" className="h-4 w-4"/></IconButton>}</div>},
 ];
 const columns=allColumns.filter(c=>visibleColumns.includes(c.key));
 const applyBulk=()=>{if(!bulkAction||selected.length===0)return;setLoading(true);router.put("/admin/users/bulk",{ids:selected,action:bulkAction},{preserveScroll:true,onFinish:()=>{setLoading(false);setSelected([]);setBulkAction("")}})};
 return <AdminLayout><Head title="Users"/><PageHeader eyebrow="Identity" title="Users" description="Manage identities, status, verification and role assignments from one controlled workspace." actions={can.create?<ButtonLink href="/admin/users/create" leadingIcon={<Icon name="plus" className="h-4 w-4"/>}>Add user</ButtonLink>:undefined}/>
 <DataTable loading={loading} rows={users.data} sort={sort?{key:sort,direction}:undefined} onSort={key=>{const nextDirection=sort===key&&direction==="asc"?"desc":"asc";setSort(key);setDirection(nextDirection);setLoading(true);router.get("/admin/users",{search:search||undefined,status:status||undefined,sort:key,direction:nextDirection},{preserveState:true,preserveScroll:true,replace:true,onFinish:()=>setLoading(false)})}} columns={columns} paginator={users} selected={selected} onSelectionChange={setSelected} empty={<EmptyState title="No users found" description="Try a different search or status filter."/>} toolbar={<div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><form className="grid flex-1 gap-3 sm:grid-cols-[minmax(0,1fr)_180px_auto]" onSubmit={submit}><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or email" leadingIcon={<Icon name="search" className="h-4 w-4"/>}/><Select value={status} onChange={setStatus} ariaLabel="Filter by status" options={[{value:"",label:"All statuses"},{value:"active",label:"Active"},{value:"suspended",label:"Suspended"}]}/><Button type="submit" variant="secondary" loading={loading}>Apply</Button></form><div className="flex flex-wrap items-end gap-2"><SavedViews scope="admin.users" state={{search,status,sort,direction,visibleColumns}} onApply={state=>{const nextSearch=String(state.search??"");const nextStatus=String(state.status??"");const nextSort=String(state.sort??"");const nextDirection=state.direction==="asc"?"asc":"desc";setSort(nextSort);setDirection(nextDirection);if(Array.isArray(state.visibleColumns))setVisibleColumns(state.visibleColumns.filter((v):v is string=>typeof v==="string"));setSearch(nextSearch);setStatus(nextStatus);setLoading(true);router.get("/admin/users",{search:nextSearch||undefined,status:nextStatus||undefined,sort:nextSort||undefined,direction:nextSort?nextDirection:undefined},{preserveState:true,replace:true,onFinish:()=>setLoading(false)})}}/><ColumnControls scope="admin.users" columns={allColumns.map(c=>({key:c.key,label:c.label||"Actions",required:c.key==="user"}))} visible={visibleColumns} onChange={setVisibleColumns}/>{selected.length>0&&<><div className="min-w-40"><Select ariaLabel="Bulk action" value={bulkAction} onChange={setBulkAction} options={[{value:"",label:"Bulk action"},{value:"activate",label:"Activate"},{value:"suspend",label:"Suspend"}]}/></div><Button type="button" variant="secondary" loading={loading} disabled={!bulkAction} onClick={applyBulk}>Apply</Button></>}<div className="pb-2 text-xs text-[var(--nx-text-muted)]"><span>{users.total.toLocaleString()} total</span>{selected.length>0&&<span className="ml-2"><Badge tone="brand">{selected.length} selected</Badge></span>}</div></div></div>}/>
 <ConfirmDialog open={!!deleteTarget} title="Delete user" description={deleteTarget?`Delete ${deleteTarget.name}? This removes the account and its role assignments.`:""} confirmLabel="Delete user" processing={deleting} onCancel={()=>setDeleteTarget(null)} onConfirm={()=>{if(!deleteTarget)return;setDeleting(true);router.delete(`/admin/users/${deleteTarget.id}`,{preserveScroll:true,onFinish:()=>{setDeleting(false);setDeleteTarget(null)}})}}/></AdminLayout>
}
