import { FormEvent, useState } from "react";
import { Head, router, useForm } from "@inertiajs/react";
import { AdminLayout } from "@admin/layout/AdminLayout";
import { PageHeader } from "@admin/components/PageHeader";
import { DataTable, type Column, type Paginator } from "@admin/components/data/DataTable";
import { EmptyState } from "@admin/components/LoadingStates";
import { ConfirmDialog } from "@admin/components/ConfirmDialog";
import { Icon } from "@admin/components/Icon";
import { Badge, Button, ButtonLink, Card, Input, Select, Textarea } from "@nexora/admin-ui";

type Artifact={id:string;package_identifier:string|null;package_version:string|null;artifact_sha256:string;content_sha256:string;signature_status:string;provenance_status:string;trust_tier:string;sandbox_profile:string;sbom_format:string|null;sbom_version:string|null;components_count:number;verification_error:string|null;verified_at:string|null;created_at:string|null;publisher:{name:string;key_id:string;trust_tier:string;status:string}|null;scan:{id:string;source_name:string;decision:string;risk_score:number}|null};
type Publisher={id:string;name:string;key_id:string;fingerprint_sha256:string;algorithm:string;trust_tier:string;status:string;artifacts_count:number;created_at:string|null};
type Props={artifacts:Paginator<Artifact>;publishers:Publisher[];summary:{artifacts:number;verified:number;unsigned:number;components:number;trusted_publishers:number};environment:{sodium:boolean;signature_protocol:string};canManagePublishers:boolean};

const human=(value:string)=>value.replaceAll("_"," ").replaceAll("-"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
const tone=(value:string):"success"|"warning"|"danger"|"neutral"=>value==="verified"||value==="trusted"||value==="core"||value==="active"?"success":value==="invalid"||value==="revoked"?"danger":value==="missing"||value==="untrusted"||value==="unavailable"?"warning":"neutral";

export default function SupplyChainIndex({artifacts,publishers,summary,environment,canManagePublishers}:Props){
 const form=useForm({name:"",key_id:"",public_key:"",trust_tier:"verified"});
 const [revoke,setRevoke]=useState<Publisher|null>(null);
 const [revoking,setRevoking]=useState(false);
 const submit=(e:FormEvent)=>{e.preventDefault();form.post("/admin/security/supply-chain/publishers",{preserveScroll:true,onSuccess:()=>form.reset()})};
 const columns:Column<Artifact>[]=[
  {key:"artifact",label:"Artifact",render:a=><div className="max-w-md"><p className="font-semibold text-[var(--nx-text)]">{a.package_identifier??a.scan?.source_name??"Unknown package"}{a.package_version&&<span className="ms-2 text-xs font-medium text-[var(--nx-text-muted)]">v{a.package_version}</span>}</p><code className="mt-1 block truncate text-[11px] text-[var(--nx-text-muted)]">{a.content_sha256}</code>{a.scan&&<ButtonLink href={`/admin/security/sentinel/scans/${a.scan.id}`} variant="ghost" size="sm" className="mt-2">Open Sentinel scan</ButtonLink>}</div>},
  {key:"trust",label:"Trust",render:a=><div className="grid gap-1.5"><div className="flex flex-wrap gap-1.5"><Badge tone={tone(a.trust_tier)}>{human(a.trust_tier)}</Badge><Badge tone={tone(a.signature_status)}>Signature: {human(a.signature_status)}</Badge></div><p className="text-xs text-[var(--nx-text-muted)]">{a.publisher?.name??"No verified publisher"}</p></div>},
  {key:"sbom",label:"SBOM",render:a=><div><p className="font-medium text-[var(--nx-text)]">{a.components_count} components</p><p className="text-xs text-[var(--nx-text-muted)]">{a.sbom_format??"—"} {a.sbom_version??""}</p></div>},
  {key:"provenance",label:"Provenance",render:a=><Badge tone={tone(a.provenance_status)}>{human(a.provenance_status)}</Badge>},
  {key:"sandbox",label:"Execution policy",render:a=><div><p className="font-medium text-[var(--nx-text)]">{human(a.sandbox_profile)}</p>{a.verification_error&&<p className="mt-1 max-w-xs text-xs leading-5 text-[var(--nx-text-muted)]">{a.verification_error}</p>}</div>},
 ];
 return <AdminLayout><Head title="Supply Chain Security"/><PageHeader eyebrow="Nexora Sentinel" title="Supply Chain Security" description="Inventory dependencies, verify publisher signatures and provenance, and assign explicit execution trust profiles before extensions can enter the runtime." actions={<ButtonLink href="/admin/security/sentinel" variant="secondary">Sentinel scans</ButtonLink>}/>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Artifacts",summary.artifacts],["Verified",summary.verified],["Unsigned",summary.unsigned],["Components",summary.components],["Trusted publishers",summary.trusted_publishers]].map(([label,value])=><Card key={label} className="p-5"><p className="text-sm font-medium text-[var(--nx-text-muted)]">{label}</p><p className="mt-3 text-3xl font-semibold text-[var(--nx-text)]">{value}</p></Card>)}</div>
 <Card className="p-5 sm:p-6"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[var(--nx-surface-subtle)]"><Icon name="shield" className="h-5 w-5"/></div><div><h2 className="font-semibold text-[var(--nx-text)]">Verification runtime</h2><p className="mt-1 text-sm leading-6 text-[var(--nx-text-secondary)]">{environment.signature_protocol}</p><p className="mt-2 text-xs text-[var(--nx-text-muted)]">PHP Sodium: <strong className="text-[var(--nx-text)]">{environment.sodium?"Available":"Unavailable"}</strong>. Unverified artifacts remain deny-execution.</p></div></div></Card>
 <DataTable rows={artifacts.data} columns={columns} paginator={artifacts} empty={<EmptyState title="No supply-chain artifacts yet" description="Rescan or upload a package in Sentinel. N0.28 will generate or ingest its SBOM and evaluate signature/provenance trust."/>}/>
 <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_26rem]"><Card className="overflow-hidden"><div className="border-b border-[var(--nx-border)] p-5"><h2 className="font-semibold text-[var(--nx-text)]">Trusted publisher keys</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">Only public Ed25519 verification keys are stored. Private signing keys stay with the publisher.</p></div><div className="divide-y divide-[var(--nx-border)]">{publishers.length?publishers.map(p=><div key={p.id} className="flex items-start justify-between gap-4 p-5"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-[var(--nx-text)]">{p.name}</p><Badge tone={tone(p.status)}>{human(p.status)}</Badge><Badge tone={tone(p.trust_tier)}>{human(p.trust_tier)}</Badge></div><p className="mt-1 text-xs text-[var(--nx-text-muted)]">Key ID: {p.key_id} · {p.artifacts_count} artifact{p.artifacts_count===1?"":"s"}</p><code className="mt-2 block truncate text-[11px] text-[var(--nx-text-muted)]">SHA-256 {p.fingerprint_sha256}</code></div>{canManagePublishers&&p.status==="active"&&<Button variant="secondary" size="sm" onClick={()=>setRevoke(p)}>Revoke</Button>}</div>):<div className="p-8 text-center text-sm text-[var(--nx-text-muted)]">No publisher keys are trusted yet.</div>}</div></Card>
 {canManagePublishers&&<Card className="h-fit p-5"><h2 className="font-semibold text-[var(--nx-text)]">Add publisher key</h2><form className="mt-4 grid gap-4" onSubmit={submit}><Input label="Publisher name" value={form.data.name} onChange={e=>form.setData("name",e.target.value)} error={form.errors.name}/><Input label="Key ID" value={form.data.key_id} onChange={e=>form.setData("key_id",e.target.value)} error={form.errors.key_id} hint="Stable identifier embedded in nexora.signature.json."/><Select label="Trust tier" value={form.data.trust_tier} onChange={v=>form.setData("trust_tier",v)} options={[{value:"verified",label:"Verified",description:"Identity key is known; execution stays restricted."},{value:"trusted",label:"Trusted",description:"Eligible for capability-gated execution after verified signing."}]}/><Textarea label="Ed25519 public key (Base64)" value={form.data.public_key} onChange={e=>form.setData("public_key",e.target.value)} error={form.errors.public_key} rows={4}/><Button type="submit" loading={form.processing} leadingIcon={<Icon name="key" className="h-4 w-4"/>}>Trust publisher key</Button></form></Card>}</div>
 <ConfirmDialog open={!!revoke} title="Revoke publisher key?" description={revoke?`Revoke ${revoke.name} (${revoke.key_id})? Historical verification records remain, but new artifacts cannot verify against this key.`:""} confirmLabel="Revoke key" danger processing={revoking} onCancel={()=>setRevoke(null)} onConfirm={()=>{if(!revoke)return;setRevoking(true);router.patch(`/admin/security/supply-chain/publishers/${revoke.id}/revoke`,{}, {preserveScroll:true,onFinish:()=>{setRevoking(false);setRevoke(null)}})}}/>
 </AdminLayout>;
}
