<?php

declare(strict_types=1);
/** @return array{errors:list<string>,warnings:list<string>,metrics:array<string,int>} */
function nexoraAnalyzeN10C5Contracts(string $root): array
{
    $errors=[];$required=['config/nexora-browser-certification.php','scripts/n1-c5-browser-performance-certify.php','scripts/n1-c5-browser-performance-certify.bat','scripts/n1-c5-browser-performance-certify.ps1','scripts/n1-c5-browser-performance-certify.sh','scripts/n1-c5-evidence-prepare.php','scripts/n1-c5-evidence-import.php','scripts/n1-c5-browser-evidence-verify.php','scripts/n1-c5-web-vitals-evidence-verify.php','scripts/n1-c5-web-standards-certify.php','scripts/n1-c5-web-standards-evidence-verify.php','scripts/n1-c5-evidence-verify.php','scripts/lib/n1-c5-browser-performance.php','NEXORA_ACCESSIBILITY_CERTIFICATION_PLAN.md'];foreach($required as $file)if(!is_file($root.'/'.$file)||filesize($root.'/'.$file)===0)$errors[]="Missing C5 artifact [{$file}].";
    $runner=(string)@file_get_contents($root.'/scripts/n1-c5-browser-performance-certify.php');$gates=['c2-evidence','browser-source','performance-source','security-source','build-assets','http-performance','web-standards','web-standards-evidence','c5-evidence'];foreach($gates as $gate)if(!str_contains($runner,"'{$gate}'"))$errors[]="C5 runner missing ordered gate [{$gate}].";foreach(['n1-c2-evidence-verify.php','browser-ux-contract-verify.php','performance-contract-verify.php','security-contract-verify.php','performance-build-verify.php','http-smoke.php','n1-c5-web-standards-certify.php','n1-c5-web-standards-evidence-verify.php','n1-c5-evidence-verify.php','--w3c-css-validator-url='] as $marker)if(!str_contains($runner,$marker))$errors[]="C5 runner missing certification marker [{$marker}].";foreach(['composer install','composer update','npm ci','npm install','certify-database-matrix.php','n1-c4-operations-certify.php','ha-evidence-verify.php'] as $forbidden)if(stripos($runner,$forbidden)!==false)$errors[]="C5 must not own C1/C3/C4/C6 gate [{$forbidden}].";
    $config=require $root.'/config/nexora-browser-certification.php';if(count((array)$config['browsers'])!==3)$errors[]='C5 requires exactly Chrome, Edge and Firefox coverage.';$matrix=count((array)$config['browsers'])*count((array)$config['viewports'])*count((array)$config['directions'])*count((array)$config['themes']);if($matrix!==36)$errors[]='C5 browser matrix must contain 36 required combinations.';$standardsRoutes=(array)($config['standards']['routes']??[]);foreach(['/','/login'] as $route)if(!in_array($route,$standardsRoutes,true))$errors[]="C5 standards route [{$route}] is required.";if((int)($config['standards']['w3c']['max_errors']??-1)!==0)$errors[]='W3C HTML project gate must require zero errors.';if((int)($config['standards']['w3c_css']['max_errors']??-1)!==0||($config['standards']['w3c_css']['profile']??null)!=='css3')$errors[]='W3C CSS project gate must require CSS3 profile and zero errors.';if((int)($config['standards']['wave']['max_errors']??-1)!==0||(int)($config['standards']['wave']['max_contrast_errors']??-1)!==0||($config['standards']['wave']['require_alert_review']??null)!==true)$errors[]='WAVE project gate must require zero errors, zero contrast errors and human alert review.';
    $prepare=(string)@file_get_contents($root.'/scripts/n1-c5-evidence-prepare.php');foreach(['browser-evidence.json','web-vitals-evidence.json',"'fail'",'assistive_technology','certification_session_id','RUNBOOK.md'] as $marker)if(!str_contains($prepare,$marker))$errors[]="C5 evidence kit missing fail-closed marker [{$marker}].";
    $verify=(string)@file_get_contents($root.'/scripts/n1-c5-evidence-verify.php');$bindings=['c2_evidence_sha256','composer_lock_sha256','package_lock_sha256','reviewed_locks_sha256','certified_toolchain_sha256','browser_evidence_sha256','web_vitals_evidence_sha256','web_standards_evidence_sha256','http_performance_sha256','build_assets_sha256','certification_session_sha256'];foreach($bindings as $binding)if(!str_contains($verify,$binding))$errors[]="C5 evidence verifier missing binding [{$binding}].";
    $standards=(string)@file_get_contents($root.'/scripts/n1-c5-web-standards-certify.php');foreach(['validator.w3.org/nu/','jigsaw.w3.org/css-validator/validator','output' => 'soap12','profile' => 'css3','wave.webaim.org/api/request','WAVE_API_KEY','--wave-alerts-reviewed','not_an_accessibility_approval','web-standards-evidence.json'] as $marker)if(!str_contains($standards,$marker))$errors[]="C5 W3C/WAVE runner missing marker [{$marker}].";
    $standardsVerify=(string)@file_get_contents($root.'/scripts/n1-c5-web-standards-evidence-verify.php');foreach(['zero conformance errors','zero validation errors','zero errors','zero contrast errors','alerts must be human-reviewed','not_an_accessibility_approval'] as $marker)if(!str_contains($standardsVerify,$marker))$errors[]="C5 W3C/WAVE verifier missing fail-closed marker [{$marker}].";
    $http=(string)@file_get_contents($root.'/scripts/http-smoke.php');foreach(['--require-base-url','--base-url=','x-content-type-options','strict-transport-security'] as $marker)if(!str_contains(strtolower($http),strtolower($marker)))$errors[]="C5 strict HTTP smoke missing marker [{$marker}].";
    $release=(string)@file_get_contents($root.'/config/nexora-release.php');if(!str_contains($release,'storage/app/nexora/n1-c5/'))$errors[]='Release policy must exclude C5 runtime evidence.';$zero=(string)@file_get_contents($root.'/scripts/zero-state-verify.php');if(!str_contains($zero,'storage/app/nexora/n1-c5'))$errors[]='Strict zero-state must reject C5 runtime evidence.';
    return ['errors'=>$errors,'warnings'=>[],'metrics'=>['wrappers'=>count(array_filter(['scripts/n1-c5-browser-performance-certify.bat','scripts/n1-c5-browser-performance-certify.ps1','scripts/n1-c5-browser-performance-certify.sh'],fn($f)=>is_file($root.'/'.$f))),'ordered_gates'=>count($gates),'browsers'=>count((array)$config['browsers']),'matrix_rows'=>$matrix,'accessibility_checks'=>count((array)$config['checks']),'standards_routes'=>count($standardsRoutes),'web_vital_metrics'=>count((array)$config['web_vitals']['thresholds']),'evidence_bindings'=>count($bindings),'dependency_installs'=>preg_match('/composer install|npm ci/i',$runner)===1?1:0,'db_c4_ha_calls'=>preg_match('/certify-database-matrix|n1-c4-operations|ha-evidence/i',$runner)===1?1:0]];
}
