<?php

declare(strict_types=1);

/** @return array{errors:list<string>,warnings:list<string>,metrics:array<string,int>} */
function nexoraAnalyzeN10C6Contracts(string $root): array
{
    $errors=[];
    $required=[
        'scripts/n1-c6-final-certify.php','scripts/n1-c6-final-certify.bat','scripts/n1-c6-final-certify.ps1','scripts/n1-c6-final-certify.sh',
        'scripts/n1-c6-evidence-prepare.php','scripts/n1-c6-ha-evidence-import.php','scripts/n1-c6-evidence-verify.php',
        'scripts/lib/n1-c6-final.php','scripts/final-target-run.php','scripts/final-evidence-verify.php','scripts/release-artifact-verify.php','scripts/closure-dashboard.php',
        'scripts/ha-evidence-verify.php','scripts/n1-c6-target-url-verify.php','scripts/lib/final-release-seal.php','scripts/final-release-seal-verify.php','scripts/n1-certification-session.php','scripts/release-signing-key.php','scripts/release-offline-verify.php','config/nexora-ha.php','config/nexora-release-trust.php',
    ];
    foreach($required as $file)if(!is_file($root.'/'.$file)||filesize($root.'/'.$file)===0)$errors[]="Missing C6 artifact [{$file}].";
    $runner=(string)@file_get_contents($root.'/scripts/n1-c6-final-certify.php');
    $gates=['c1-evidence','c2-evidence','c3-evidence','c4-evidence','c5-evidence','ha-source','ha-readiness','ha-rehearsal','ha-evidence','target-url-consistency','target-evidence-intake','release-signing-readiness','release-trust-anchor','production-runtime-stage','release-provenance','final-target','production-artifact','session-finalize','closure-dashboard','c6-evidence'];
    foreach($gates as $gate)if(!str_contains($runner,"'{$gate}'"))$errors[]="C6 runner missing ordered gate [{$gate}].";
    foreach(['n1-c1-evidence-verify.php','n1-c2-evidence-verify.php','n1-c3-database-matrix-evidence-verify.php','n1-c4-evidence-verify.php','n1-c5-evidence-verify.php','nexora:ha:status','nexora:ha:rehearse','n1-c6-target-url-verify.php','target-evidence-intake.php','--require-complete','release-signing-key.php','release-trust-anchor.php','production-dependency-stage.php','--build','release-provenance.php','final-target-run.php','--final','release-artifact-verify.php','n1-certification-session.php','--finalize','closure-dashboard.php','n1-c6-evidence-verify.php'] as $marker)if(!str_contains($runner,$marker))$errors[]="C6 runner missing release marker [{$marker}].";
    foreach(['composer update','npm install','dependency-lock-review.php\',\'--accept','migrate:fresh','migrate:reset'] as $forbidden)if(stripos($runner,$forbidden)!==false)$errors[]="C6 must not directly mutate dependency locks or own destructive DB commands [{$forbidden}].";
    $final=(string)@file_get_contents($root.'/scripts/final-evidence-verify.php');foreach(['nexoraValidateN10C6ChunkEvidence','chunk_evidence'] as $marker)if(!str_contains($final,$marker))$errors[]="Final evidence must enforce C1-C5 chunk closure marker [{$marker}].";
    $prepare=(string)@file_get_contents($root.'/scripts/n1-c6-evidence-prepare.php');foreach(["'fail'",'ha-evidence.json','certification_session_id','RUNBOOK.md','node-example'] as $marker)if(!str_contains($prepare,$marker))$errors[]="C6 HA evidence kit missing fail-closed marker [{$marker}].";
    $nodeResourceMarkers=['runtime_resource_fingerprint','resource_deep_probe_sha256','resource_status','runtime_process_fingerprint','runtime_process_policy_status'];foreach($nodeResourceMarkers as $marker)if(!str_contains($prepare,$marker))$errors[]="C6 HA node resource evidence missing [{$marker}].";
    $haChecks=['shared_cache_cross_node','shared_session_cross_node','shared_object_storage_cross_node','async_queue_distribution','scheduler_single_leader','scheduler_failover','node_drain_readiness','worker_drain_restart','node_failure_recovery','version_consistency','deployment_generation_consistency','deep_deployment_integrity_each_node','cache_generation_namespace_consistency','session_schema_consistency','runtime_environment_fingerprint_consistency','runtime_activation_epoch_cache_consistency','runtime_engine_fingerprint_consistency','runtime_database_data_plane_consistency','runtime_storage_data_plane_consistency','shared_backup_storage_cross_node','runtime_service_data_plane_consistency','runtime_host_profile_consistency','database_clock_skew_within_limit','runtime_resource_policy_consistency','runtime_resource_capacity_minimums','runtime_policy_plane_consistency','runtime_policy_status_pass','runtime_process_policy_consistency','web_process_quorum','queue_process_quorum','scheduler_process_quorum','laravel_framework_version_consistency','runtime_dependency_fingerprint_consistency','dependency_review_status_pass'];foreach($haChecks as $check)if(!str_contains($prepare,"'{$check}'"))$errors[]="C6 HA evidence kit missing required check [{$check}].";
    $verify=(string)@file_get_contents($root.'/scripts/n1-c6-evidence-verify.php');$bindings=['c1_evidence_sha256','c2_evidence_sha256','c3_evidence_sha256','c4_evidence_sha256','c5_evidence_sha256','ha_evidence_sha256','target_evidence_intake_sha256','final_evidence_sha256','closure_status_sha256','production_package_sha256','certification_session_sha256','release_seal_sha256','release_signature_sha256','release_public_key_sha256','release_trust_anchor_sha256','dependency_sbom_sha256','production_dependencies_sha256','release_provenance_sha256','certification_session_finalization_sha256','certified_toolchain_sha256','certification_evidence_bundle_sha256'];foreach($bindings as $binding)if(!str_contains($verify,$binding))$errors[]="C6 evidence verifier missing binding [{$binding}].";
    $release=(string)@file_get_contents($root.'/config/nexora-release.php');if(!str_contains($release,'storage/app/nexora/n1-c6/'))$errors[]='Release policy must exclude C6 runtime evidence.';
    $zero=(string)@file_get_contents($root.'/scripts/zero-state-verify.php');if(!str_contains($zero,'storage/app/nexora/n1-c6'))$errors[]='Strict zero-state must reject C6 runtime evidence.';
    return ['errors'=>$errors,'warnings'=>[],'metrics'=>['wrappers'=>count(array_filter(['scripts/n1-c6-final-certify.bat','scripts/n1-c6-final-certify.ps1','scripts/n1-c6-final-certify.sh'],fn($f)=>is_file($root.'/'.$f))),'ordered_gates'=>count($gates),'prior_chunks'=>5,'ha_checks'=>count($haChecks),'evidence_bindings'=>count($bindings),'direct_dependency_lock_mutations'=>preg_match('/composer update|npm install|--accept/i',$runner)===1?1:0,'direct_destructive_db_calls'=>preg_match('/migrate:fresh|migrate:reset/i',$runner)===1?1:0]];
}
