<?php

declare(strict_types=1);
function nexoraAnalyzeN10C2Contracts(string $root):array{
 $errors=[];$runner=(string)@file_get_contents($root.'/scripts/n1-c2-laravel-runtime-certify.php');
 $required=['scripts/n1-c1-evidence-verify.php','scripts/n1-c2-laravel-runtime-certify.php','scripts/n1-c2-laravel-runtime-certify.bat','scripts/n1-c2-laravel-runtime-certify.ps1','scripts/n1-c2-laravel-runtime-certify.sh','scripts/n1-c2-evidence-verify.php'];foreach($required as $f)if(!is_file($root.'/'.$f))$errors[]="Missing {$f}.";
 $gates=['c1-evidence','installed-dependencies','package-discover','installation-lock-status','installation-lock-integrity-test','installation-bootstrap-receipt-test','installation-lock-http-failclosed-test','installer-consent-flow-test','installation-resume-provenance-test','password-risk-consent-test','optimize-clear-before','artisan-about','route-list','schedule-list','database-prepare','database-version-doctor','migrate-fresh-seed','seed-idempotency','tenant-seed-isolation-test','tenant-execution-boundary-test','database-data-plane-baseline','migration-reset','migration-rebuild','seed-rebuild','database-data-plane-rebuild','runtime-sync','runtime-cache','database-isolation-test','environment-doctor','filesystem-doctor','transfer-doctor','runtime-doctor','runtime-engine-status','database-data-plane-status','runtime-storage-status','runtime-service-status','runtime-host-status','runtime-resource-status','runtime-policy-status','runtime-process-status','runtime-dependency-status','runtime-compatibility-status','concurrency-doctor','phpunit-full','pint','artisan-optimize','optimized-about','optimized-route-list','optimized-schedule-list','optimized-environment-doctor','optimized-database-doctor','optimize-clear-final'];
 foreach($gates as $g)if(!str_contains($runner,"'{$g}'"))$errors[]="C2 runner missing ordered gate [{$g}].";
 foreach(['database-data-plane-certify.php','NEXORA_CERT_EXPECT_DB_CONNECTION','NEXORA_CERT_EXPECT_DB_DATABASE','nexora_certification','create-certification-database.php'] as $m)if(!str_contains($runner,$m))$errors[]="C2 isolation boundary missing [{$m}].";
 $prepare=strpos($runner,"'database-prepare'");$fresh=strpos($runner,"'migrate-fresh-seed'");$reset=strpos($runner,"'migration-reset'");if($prepare===false||$fresh===false||$reset===false||!($prepare<$fresh&&$prepare<$reset))$errors[]='C2 must prepare/guard the isolated certification database before destructive migration commands.';
 foreach(['composer install','composer update','npm ci','npm install','dependency-lock-review.php\',\'--accept','refresh-dependency-locks','certify-database-matrix.php','browser-evidence-verify.php','ha-evidence-verify.php','backup-restore-evidence-verify.php'] as $forbidden)if(stripos($runner,$forbidden)!==false)$errors[]="C2 must not own dependency install/C3+/operator gates [{$forbidden}].";
 $release=(string)@file_get_contents($root.'/config/nexora-release.php');if(!str_contains($release,'storage/app/nexora/n1-c2/'))$errors[]='Release policy must exclude C2 runtime evidence.';
 $zero=(string)@file_get_contents($root.'/scripts/zero-state-verify.php');if(!str_contains($zero,'storage/app/nexora/n1-c2'))$errors[]='Strict zero-state must reject C2 runtime evidence.';
 return ['errors'=>$errors,'warnings'=>[],'metrics'=>['wrappers'=>count(array_filter(['scripts/n1-c2-laravel-runtime-certify.bat','scripts/n1-c2-laravel-runtime-certify.ps1','scripts/n1-c2-laravel-runtime-certify.sh'],fn($f)=>is_file($root.'/'.$f))),'ordered_gates'=>count($gates),'direct_dependency_installs'=>preg_match('/composer install|npm ci/i',$runner)===1?1:0,'db_matrix_calls'=>str_contains($runner,'certify-database-matrix.php')?1:0,'operator_evidence_calls'=>preg_match('/browser-evidence|ha-evidence|backup-restore-evidence/i',$runner)===1?1:0]];
}
