<?php

declare(strict_types=1);require_once __DIR__.'/source-attestation.php';require_once __DIR__.'/target-composer.php';require_once __DIR__.'/n1-certified-toolchain.php';
function nexoraProductionDependencyStageDir(string $root): string { $p=require $root.'/config/nexora-supply-chain.php';return $root.'/'.trim((string)($p['production_dependencies']['stage_dir']??'storage/app/nexora/release-stage/php-runtime'),'/'); }
function nexoraProductionDependencyEvidencePath(string $root): string { return $root.'/storage/app/nexora/certification/production-dependencies.json'; }
/** @return array{sha256:string,file_count:int,total_bytes:int} */
function nexoraDirectoryContentFingerprint(string $dir): array { $rows=[];$total=0;if(!is_dir($dir))return ['sha256'=>hash('sha256',''),'file_count'=>0,'total_bytes'=>0];$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::LEAVES_ONLY);foreach($it as $f){if(!$f->isFile())continue;$rel=str_replace('\\','/',substr($f->getPathname(),strlen($dir)+1));$sha=hash_file('sha256',$f->getPathname())?:'';$size=$f->getSize();$total+=$size;$rows[]=$rel."\0".$sha."\0".$size;}sort($rows,SORT_STRING);return ['sha256'=>hash('sha256',implode("\n",$rows)),'file_count'=>count($rows),'total_bytes'=>$total]; }
function nexoraRemoveTree(string $path): void { if(!file_exists($path))return;$real=str_replace('\\','/',$path);if(!str_contains($real,'/storage/app/nexora/release-stage/'))throw new RuntimeException('refusing to remove path outside release-stage');$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $f){$f->isDir()?rmdir($f->getPathname()):unlink($f->getPathname());}rmdir($path); }
/** @return array<string,mixed> */
function nexoraBuildProductionDependencyStage(string $root): array { foreach(['composer.json','composer.lock'] as $f)if(!is_file($root.'/'.$f))throw new RuntimeException("{$f} missing");$stage=nexoraProductionDependencyStageDir($root);if(is_dir($stage))nexoraRemoveTree($stage);if(!mkdir($stage,0775,true)&&!is_dir($stage))throw new RuntimeException('unable to create production dependency stage');copy($root.'/composer.json',$stage.'/composer.json');copy($root.'/composer.lock',$stage.'/composer.lock');$tool=nexoraLocateTargetComposer($root);$cmd=(array)($tool['command']??[]);if($cmd===[])throw new RuntimeException('trusted Composer unavailable for production no-dev stage');$parts=array_merge($cmd,['install','--no-dev','--no-scripts','--no-interaction','--prefer-dist','--optimize-autoloader','--no-progress']);$line=implode(' ',array_map('escapeshellarg',$parts));$proc=proc_open($line,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$stage,null);if(!is_resource($proc))throw new RuntimeException('unable to start Composer production stage');fclose($pipes[0]);$out=(string)stream_get_contents($pipes[1]);fclose($pipes[1]);$err=(string)stream_get_contents($pipes[2]);fclose($pipes[2]);$code=proc_close($proc);if($code!==0)throw new RuntimeException('Composer --no-dev stage failed: '.trim(substr($err!==''?$err:$out,-2000)));if(!is_file($stage.'/vendor/autoload.php'))throw new RuntimeException('production stage vendor/autoload.php missing');
    $lock=json_decode((string)file_get_contents($root.'/composer.lock'),true,512,JSON_THROW_ON_ERROR);$prod=[];foreach((array)($lock['packages']??[]) as $p)if(is_array($p)&&isset($p['name']))$prod[(string)$p['name']]=true;$dev=[];foreach((array)($lock['packages-dev']??[]) as $p)if(is_array($p)&&isset($p['name'])&&!isset($prod[(string)$p['name']]))$dev[(string)$p['name']]=true;$installedPath=$stage.'/vendor/composer/installed.json';if(!is_file($installedPath))throw new RuntimeException('production stage installed.json missing');$installed=json_decode((string)file_get_contents($installedPath),true,512,JSON_THROW_ON_ERROR);$rows=is_array($installed['packages']??null)?$installed['packages']:(is_array($installed)?$installed:[]);$names=[];foreach($rows as $p)if(is_array($p)&&isset($p['name']))$names[(string)$p['name']]=true;foreach(array_keys($dev) as $name)if(isset($names[$name]))throw new RuntimeException("dev-only Composer package leaked into production stage [{$name}]");foreach(array_keys($prod) as $name)if(!isset($names[$name]))throw new RuntimeException("required Composer package missing from production stage [{$name}]");$fp=nexoraDirectoryContentFingerprint($stage.'/vendor');$source=nexoraComputeSourceAttestation($root);$toolchain=nexoraCertifiedToolchainPath($root);$payload=['schema'=>1,'status'=>'pass','platform_version'=>(string)((require $root.'/config/nexora.php')['version']??'unknown'),'source_tree_sha256'=>$source['tree_sha256'],'composer_lock_sha256'=>hash_file('sha256',$root.'/composer.lock'),'certified_toolchain_sha256'=>is_file($toolchain)?hash_file('sha256',$toolchain):null,'composer_no_dev'=>true,'composer_no_scripts'=>true,'package_count'=>count($names),'vendor_tree_sha256'=>$fp['sha256'],'vendor_file_count'=>$fp['file_count'],'vendor_total_bytes'=>$fp['total_bytes'],'checked_at'=>gmdate(DATE_ATOM)];$path=nexoraProductionDependencyEvidencePath($root);$dir=dirname($path);if(!is_dir($dir)&&!mkdir($dir,0775,true)&&!is_dir($dir))throw new RuntimeException('unable to create certification directory');file_put_contents($path,json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL);return $payload; }
/** @return list<string> */
function nexoraValidateProductionDependencyStage(string $root): array { $errors=[];$stage=nexoraProductionDependencyStageDir($root);$path=nexoraProductionDependencyEvidencePath($root);if(!is_file($path))return ['production dependency evidence missing'];try{$d=json_decode((string)file_get_contents($path),true,128,JSON_THROW_ON_ERROR);}catch(Throwable $e){return ['invalid production dependency evidence: '.$e->getMessage()];}if(($d['status']??null)!=='pass'||($d['schema']??null)!==1)$errors[]='production dependency evidence schema/status invalid';$source=nexoraComputeSourceAttestation($root);if(($d['source_tree_sha256']??null)!==$source['tree_sha256'])$errors[]='production dependency evidence source mismatch';if(($d['composer_lock_sha256']??null)!==hash_file('sha256',$root.'/composer.lock'))$errors[]='production dependency evidence Composer lock mismatch';if(!is_file($stage.'/vendor/autoload.php'))$errors[]='production staged vendor/autoload.php missing';else{$fp=nexoraDirectoryContentFingerprint($stage.'/vendor');if(($d['vendor_tree_sha256']??null)!==$fp['sha256'])$errors[]='production vendor tree hash mismatch';}return $errors; }
