import { useMemo, useState } from "react";
import { Head, router, useForm } from "@inertiajs/react";
import { AdminLayout } from "@admin/layout/AdminLayout";
import { PageHeader } from "@admin/components/PageHeader";
import { DataTable, type Column, type Paginator } from "@admin/components/data/DataTable";
import { EmptyState } from "@admin/components/LoadingStates";
import { Badge, Button, Card, Input, Modal, Select, Textarea } from "@nexora/admin-ui";
import { CommerceNav } from "./_CommerceNav";
type Row={id:string;name:string;sku:string|null;slug:string;type:string;status:string;prices:Array<{id:string;currency:string;amount:string;billing_interval:string|null}>;created_at:string|null};
type Currency={code:string;name:string;symbol:string|null;minor_unit:number};
type Props={products:Paginator<Row>;currencies:Currency[];canManage:boolean};
const human=(v:string)=>v.replace(/[_-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function Products({products,currencies,canManage}:Props){
 const [open,setOpen]=useState(false); const [priceFor,setPriceFor]=useState<Row|null>(null);
 const form=useForm({name:"",sku:"",slug:"",type:"product",status:"draft",description:"",tax_code:"",currency:currencies[0]?.code??"USD",amount:"",billing_interval:""});
 const price=useForm({currency:currencies[0]?.code??"USD",amount:"",billing_interval:""});
 const columns=useMemo<Column<Row>[]>(()=>[
  {key:"product",label:"Product",render:r=><div><p className="font-semibold text-[var(--nx-text)]">{r.name}</p><p className="mt-1 text-xs text-[var(--nx-text-muted)]">{r.sku??"No SKU"} · {human(r.type)}</p></div>},
  {key:"status",label:"Status",render:r=><Badge tone={r.status==="active"?"success":r.status==="archived"?"neutral":"warning"}>{human(r.status)}</Badge>},
  {key:"prices",label:"Prices",render:r=><div className="grid gap-1">{r.prices.length===0?<span className="text-xs text-[var(--nx-text-muted)]">No active price</span>:r.prices.map(p=><span key={p.id} className="text-sm text-[var(--nx-text-secondary)]">{p.amount}{p.billing_interval?` / ${human(p.billing_interval)}`:""}</span>)}</div>},
  {key:"actions",label:"",className:"w-40 text-right",render:r=>canManage?<div className="flex justify-end gap-2"><Button size="sm" variant="secondary" onClick={()=>setPriceFor(r)}>Add price</Button><Button size="sm" variant="secondary" onClick={()=>router.patch(`/admin/commerce/products/${r.id}/status`,{status:r.status==="active"?"archived":"active"},{preserveScroll:true})}>{r.status==="active"?"Archive":"Activate"}</Button></div>:null},
 ],[canManage]);
 return <AdminLayout><Head title="Commerce Products"/><PageHeader eyebrow="Commerce" title="Products & prices" description="Products are provider-neutral. Prices store integer minor-unit values internally and can be one-time or recurring." actions={canManage?<Button onClick={()=>setOpen(true)}>Create product</Button>:undefined}/><CommerceNav current="/admin/commerce/products"/>
 <DataTable rows={products.data} columns={columns} paginator={products} empty={<EmptyState title="No products" description="Create the first sellable product, service or digital offer."/>}/>
 <Modal open={open} onClose={()=>setOpen(false)} title="Create product" description="Create a product and its first price." footer={<><Button variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={form.processing} onClick={()=>form.post('/admin/commerce/products',{preserveScroll:true,onSuccess:()=>{form.reset();setOpen(false)}})}>Create product</Button></>}><div className="grid gap-4"><Input label="Product name" value={form.data.name} onChange={e=>form.setData('name',e.target.value)} error={form.errors.name}/><div className="grid gap-4 sm:grid-cols-2"><Input label="SKU" value={form.data.sku} onChange={e=>form.setData('sku',e.target.value)} hint="Optional internal identifier."/><Input label="Slug" value={form.data.slug} onChange={e=>form.setData('slug',e.target.value)} hint="Leave empty for automatic slug."/></div><div className="grid gap-4 sm:grid-cols-2"><Select label="Product type" value={form.data.type} onChange={v=>form.setData('type',v)} options={[{value:'product',label:'Product'},{value:'service',label:'Service'},{value:'digital',label:'Digital product'}]}/><Select label="Status" value={form.data.status} onChange={v=>form.setData('status',v)} options={[{value:'draft',label:'Draft'},{value:'active',label:'Active'},{value:'archived',label:'Archived'}]}/></div><Textarea label="Description" value={form.data.description} onChange={e=>form.setData('description',e.target.value)}/><Input label="Tax code" value={form.data.tax_code} onChange={e=>form.setData('tax_code',e.target.value)} hint="Optional identifier matched by Commerce tax rules."/><div className="grid gap-4 sm:grid-cols-3"><Select label="Currency" value={form.data.currency} onChange={v=>form.setData('currency',v)} options={currencies.map(c=>({value:c.code,label:`${c.code} — ${c.name}`}))}/><Input label="Price" value={form.data.amount} onChange={e=>form.setData('amount',e.target.value)} placeholder="0.00" error={form.errors.amount}/><Select label="Billing" value={form.data.billing_interval} onChange={v=>form.setData('billing_interval',v)} options={[{value:'',label:'One-time'},{value:'monthly',label:'Monthly'},{value:'yearly',label:'Yearly'}]}/></div></div></Modal>
 <Modal open={Boolean(priceFor)} onClose={()=>setPriceFor(null)} title={`Add price${priceFor?` — ${priceFor.name}`:""}`} footer={<><Button variant="secondary" onClick={()=>setPriceFor(null)}>Cancel</Button><Button loading={price.processing} onClick={()=>priceFor&&price.post(`/admin/commerce/products/${priceFor.id}/prices`,{preserveScroll:true,onSuccess:()=>{price.reset();setPriceFor(null)}})}>Add price</Button></>}><div className="grid gap-4"><Select label="Currency" value={price.data.currency} onChange={v=>price.setData('currency',v)} options={currencies.map(c=>({value:c.code,label:`${c.code} — ${c.name}`}))}/><Input label="Price" value={price.data.amount} onChange={e=>price.setData('amount',e.target.value)} placeholder="0.00"/><Select label="Billing" value={price.data.billing_interval} onChange={v=>price.setData('billing_interval',v)} options={[{value:'',label:'One-time'},{value:'monthly',label:'Monthly'},{value:'yearly',label:'Yearly'}]}/></div></Modal>
 </AdminLayout>;
}
