import { useState } from "react";
import { Head, router, useForm } from "@inertiajs/react";
import { AdminLayout } from "@admin/layout/AdminLayout";
import { PageHeader } from "@admin/components/PageHeader";
import { Badge, Button, Card, Checkbox, Input, Modal, Select } from "@nexora/admin-ui";
import { CommerceNav } from "./_CommerceNav";
type Currency={code:string;name:string;symbol:string|null;minor_unit:number;enabled:boolean;is_default:boolean};
type Tax={id:string;name:string;country_code:string|null;region_code:string|null;tax_code:string|null;rate_basis_points:number;inclusive:boolean;active:boolean};
type Provider={key:string;label:string;capabilities:string[]};
type Config={id:string;provider_key:string;display_name:string;enabled:boolean;mode:string;last_health_status:string|null;last_health_message:string|null;last_health_checked_at:string|null};
type Props={currencies:Currency[];taxRates:Tax[];registeredProviders:Provider[];providerConfigs:Config[]};
const human=(v:string)=>v.replace(/[_-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function Settings({currencies,taxRates,registeredProviders,providerConfigs}:Props){
 const [currencyOpen,setCurrencyOpen]=useState(false); const [taxOpen,setTaxOpen]=useState(false);
 const currency=useForm({code:"",name:"",symbol:"",minor_unit:"2",enabled:true,is_default:false});
 const tax=useForm({name:"",country_code:"",region_code:"",tax_code:"",rate_percent:"",inclusive:false,active:true});
 const provider=useForm({provider_key:"",enabled:false,mode:"live"});
 return <AdminLayout><Head title="Commerce Settings"/><PageHeader eyebrow="Commerce" title="Commerce settings" description="Manage currencies, explicit tax rules and extension-registered payment providers. Nexora does not store gateway private keys in Core."/><CommerceNav current="/admin/commerce/settings"/>
 <div className="grid gap-5 xl:grid-cols-2"><Card className="p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-[var(--nx-text)]">Currencies</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">Money is stored as integer minor units; no automatic foreign-exchange conversion is assumed.</p></div><Button size="sm" onClick={()=>setCurrencyOpen(true)}>Add currency</Button></div><div className="mt-4 grid gap-2">{currencies.map(c=><div key={c.code} className="flex items-center justify-between gap-3 rounded-xl border border-[var(--nx-border)] p-3"><div><p className="font-semibold text-[var(--nx-text)]">{c.code} — {c.name}</p><p className="text-xs text-[var(--nx-text-muted)]">{c.symbol??"No symbol"} · {c.minor_unit} decimal place{c.minor_unit===1?"":"s"}</p></div><div className="flex gap-2">{c.is_default&&<Badge tone="brand">Default</Badge>}<Badge tone={c.enabled?"success":"neutral"}>{c.enabled?"Enabled":"Disabled"}</Badge></div></div>)}</div></Card>
 <Card className="p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-[var(--nx-text)]">Tax rules</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">Explicit rules only. Configure legal/tax logic appropriate to your jurisdiction or use a future tax-provider extension.</p></div><Button size="sm" onClick={()=>setTaxOpen(true)}>Add tax rule</Button></div><div className="mt-4 grid gap-2">{taxRates.length===0?<p className="py-6 text-center text-sm text-[var(--nx-text-muted)]">No tax rule configured.</p>:taxRates.map(t=><div key={t.id} className="rounded-xl border border-[var(--nx-border)] p-3"><div className="flex items-center justify-between gap-3"><p className="font-semibold text-[var(--nx-text)]">{t.name}</p><Badge tone={t.active?"success":"neutral"}>{t.active?"Active":"Disabled"}</Badge></div><p className="mt-1 text-xs text-[var(--nx-text-muted)]">{(t.rate_basis_points/100).toFixed(2)}% · {t.inclusive?"Tax inclusive":"Tax exclusive"}{t.country_code?` · ${t.country_code}`:""}{t.region_code?` / ${t.region_code}`:""}</p></div>)}</div></Card></div>
 <Card className="mt-5 p-5 sm:p-6"><h2 className="font-semibold text-[var(--nx-text)]">Payment providers</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">Only enabled verified extensions can register a provider adapter. Core stores provider-neutral references and non-secret preferences; provider secrets remain extension-managed.</p>
 <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_1fr]"><div className="grid gap-3">{registeredProviders.length===0?<div className="rounded-xl border border-dashed border-[var(--nx-border)] p-4 text-sm text-[var(--nx-text-muted)]">No payment provider extension is registered. Install/enable a verified provider extension from Extensions when available.</div>:registeredProviders.map(p=>{const cfg=providerConfigs.find(c=>c.provider_key===p.key);return <div key={p.key} className="rounded-xl border border-[var(--nx-border)] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-[var(--nx-text)]">{p.label}</p><p className="mt-1 text-xs text-[var(--nx-text-muted)]">{p.capabilities.map(human).join(" · ")}</p></div><Badge tone={cfg?.enabled?"success":"neutral"}>{cfg?.enabled?"Enabled":"Not enabled"}</Badge></div>{cfg&&<div className="mt-3 flex gap-2"><Button size="sm" variant="secondary" onClick={()=>router.post(`/admin/commerce/settings/providers/${cfg.id}/health`,{}, {preserveScroll:true})}>Check health</Button>{cfg.last_health_status&&<Badge tone={cfg.last_health_status==="healthy"?"success":"danger"}>{human(cfg.last_health_status)}</Badge>}</div>}</div>})}</div>
 <div className="grid content-start gap-4 rounded-xl border border-[var(--nx-border)] p-4"><Select label="Registered provider" value={provider.data.provider_key} onChange={v=>provider.setData('provider_key',v)} options={registeredProviders.map(p=>({value:p.key,label:p.label,description:p.capabilities.map(human).join(' · ')}))} placeholder="Select an extension provider"/><Select label="Provider mode" value={provider.data.mode} onChange={v=>provider.setData('mode',v)} options={[{value:'live',label:'Live'},{value:'test',label:'Test / sandbox'}]}/><Checkbox label="Enable this provider" checked={provider.data.enabled} onChange={e=>provider.setData('enabled',e.target.checked)} description="Actual secret/config readiness is still validated by the provider extension."/><Button disabled={!provider.data.provider_key} loading={provider.processing} onClick={()=>provider.post('/admin/commerce/settings/providers',{preserveScroll:true})}>Save provider preference</Button></div></div></Card>
 <Modal open={currencyOpen} onClose={()=>setCurrencyOpen(false)} title="Add or update currency" footer={<><Button variant="secondary" onClick={()=>setCurrencyOpen(false)}>Cancel</Button><Button loading={currency.processing} onClick={()=>currency.post('/admin/commerce/settings/currencies',{preserveScroll:true,onSuccess:()=>{currency.reset();setCurrencyOpen(false)}})}>Save currency</Button></>}><div className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><Input label="Currency code" value={currency.data.code} onChange={e=>currency.setData('code',e.target.value.toUpperCase())} placeholder="USD" maxLength={3}/><Input label="Display name" value={currency.data.name} onChange={e=>currency.setData('name',e.target.value)} placeholder="US Dollar"/></div><div className="grid gap-4 sm:grid-cols-2"><Input label="Symbol" value={currency.data.symbol} onChange={e=>currency.setData('symbol',e.target.value)} placeholder="$"/><Input label="Decimal places" value={currency.data.minor_unit} onChange={e=>currency.setData('minor_unit',e.target.value)} inputMode="numeric"/></div><Checkbox label="Enabled" checked={currency.data.enabled} onChange={e=>currency.setData('enabled',e.target.checked)}/><Checkbox label="Default Commerce currency" checked={currency.data.is_default} onChange={e=>currency.setData('is_default',e.target.checked)}/></div></Modal>
 <Modal open={taxOpen} onClose={()=>setTaxOpen(false)} title="Add tax rule" footer={<><Button variant="secondary" onClick={()=>setTaxOpen(false)}>Cancel</Button><Button loading={tax.processing} onClick={()=>tax.post('/admin/commerce/settings/tax-rates',{preserveScroll:true,onSuccess:()=>{tax.reset();setTaxOpen(false)}})}>Create rule</Button></>}><div className="grid gap-4"><Input label="Rule name" value={tax.data.name} onChange={e=>tax.setData('name',e.target.value)} placeholder="Standard tax"/><div className="grid gap-4 sm:grid-cols-2"><Input label="Country code" value={tax.data.country_code} onChange={e=>tax.setData('country_code',e.target.value.toUpperCase())} placeholder="US" maxLength={2}/><Input label="Region code" value={tax.data.region_code} onChange={e=>tax.setData('region_code',e.target.value)} placeholder="Optional region/state"/></div><div className="grid gap-4 sm:grid-cols-2"><Input label="Tax code" value={tax.data.tax_code} onChange={e=>tax.setData('tax_code',e.target.value)} placeholder="Optional product tax code"/><Input label="Rate (%)" value={tax.data.rate_percent} onChange={e=>tax.setData('rate_percent',e.target.value)} placeholder="20.00" inputMode="decimal"/></div><Checkbox label="Price includes this tax" checked={tax.data.inclusive} onChange={e=>tax.setData('inclusive',e.target.checked)}/><Checkbox label="Active" checked={tax.data.active} onChange={e=>tax.setData('active',e.target.checked)}/></div></Modal>
 </AdminLayout>;
}
