import { useMemo, useState } from "react";
import { Head, router, useForm, usePage } from "@inertiajs/react";
import { AdminLayout } from "@admin/layout/AdminLayout";
import { PageHeader } from "@admin/components/PageHeader";
import { Icon } from "@admin/components/Icon";
import { ConfirmDialog } from "@admin/components/ConfirmDialog";
import { Badge, Button, ButtonLink, Card, FilePicker, IconButton, Input, Modal, Select, Textarea } from "@nexora/admin-ui";
import type { SharedPageProps } from "@admin/types/page";

type Asset={id:number;uuid:string;title:string;original_name:string;media_type:string;mime_type:string;size_bytes:number;width:number|null;height:number|null;alt_text:string|null;caption:string|null;description:string|null;folder:string|null;folder_id:number|null;url:string|null;variants:Record<string,string>;usages_count:number;deleted_at:string|null;created_at:string|null;uploader:string|null};
type Folder={id:number;parent_id:number|null;name:string;slug:string};
type Collection={id:number;name:string;slug:string;description:string|null;assets_count:number};
type Paginator<T>={data:T[];current_page:number;last_page:number;per_page:number;total:number;prev_page_url:string|null;next_page_url:string|null};
type Props={assets:Paginator<Asset>;filters:{search:string;type:string;folder:string|number;view:string};folders:Folder[];collections:Collection[];summary:{all:number;images:number;documents:number;trash:number};upload:{max_mb:number;accepted:string;storage_ready:boolean}};

const bytes=(value:number)=>value<1024?`${value} B`:value<1024*1024?`${(value/1024).toFixed(1)} KB`:`${(value/1024/1024).toFixed(1)} MB`;
const typeLabel=(value:string)=>value==="image"?"Image":value==="video"?"Video":value==="audio"?"Audio":"Document";

function Preview({asset}:{asset:Asset}){
 if(asset.media_type==="image"&&asset.url)return <img src={asset.url} alt={asset.alt_text??asset.title} className="h-full w-full object-cover" loading="lazy" decoding="async"/>;
 return <span className="grid h-full w-full place-items-center bg-[var(--nx-surface-subtle)] text-[var(--nx-text-muted)]"><Icon name={asset.media_type==="video"?"video":asset.media_type==="audio"?"audio":"file-text"} className="h-8 w-8"/></span>;
}

export default function MediaIndex({assets,filters,folders,collections,summary,upload}:Props){
 const permissions=usePage<SharedPageProps>().props.auth.user?.permissions??[];
 const canUpload=permissions.includes("media.upload"),canManage=permissions.includes("media.manage"),canDelete=permissions.includes("media.delete"),canForce=permissions.includes("media.delete.permanent");
 const [search,setSearch]=useState(filters.search??""); const [type,setType]=useState(filters.type??""); const [folder,setFolder]=useState(String(filters.folder??""));
 const [editing,setEditing]=useState<Asset|null>(null); const [deleting,setDeleting]=useState<Asset|null>(null); const [folderOpen,setFolderOpen]=useState(false); const [collectionOpen,setCollectionOpen]=useState(false);
 const uploadForm=useForm<{file:File|null;folder_id:string;title:string;alt_text:string;caption:string}>({file:null,folder_id:"",title:"",alt_text:"",caption:""});
 const editForm=useForm({folder_id:"",title:"",alt_text:"",caption:"",description:"",focal_x:"",focal_y:"",collection_id:""});
 const folderForm=useForm({name:"",parent_id:""}); const collectionForm=useForm({name:"",description:""});
 const folderOptions=useMemo(()=>[{value:"",label:"All folders"},...folders.map(item=>({value:String(item.id),label:item.name}))],[folders]);
 const apply=(next:Record<string,string>={})=>router.get("/admin/media",{search,type,folder,view:filters.view,...next},{preserveState:true,replace:true});
 const startEdit=(asset:Asset)=>{setEditing(asset);editForm.setData({folder_id:asset.folder_id?String(asset.folder_id):"",title:asset.title??"",alt_text:asset.alt_text??"",caption:asset.caption??"",description:asset.description??"",focal_x:"",focal_y:"",collection_id:""});};
 const saveEdit=()=>{if(!editing)return;editForm.transform(data=>({...data,folder_id:data.folder_id?Number(data.folder_id):null,focal_x:data.focal_x?Number(data.focal_x):null,focal_y:data.focal_y?Number(data.focal_y):null}));editForm.put(`/admin/media/${editing.id}`,{preserveScroll:true,onSuccess:()=>setEditing(null)});};
 const addCollection=()=>{if(!editing||!editForm.data.collection_id)return;router.post(`/admin/media/collections/${editForm.data.collection_id}/assets`,{asset_id:editing.id},{preserveScroll:true});};
 return <AdminLayout><Head title="Media Library"/><PageHeader eyebrow="Content assets" title="Media Library" description="Manage images, video, audio and documents with metadata, responsive image variants, folders, collections, usage tracking and recoverable Trash." actions={<div className="flex flex-wrap gap-2">{canManage&&<Button variant="secondary" leadingIcon={<Icon name="folder" className="h-4 w-4"/>} onClick={()=>setFolderOpen(true)}>New folder</Button>}{canManage&&<Button variant="secondary" leadingIcon={<Icon name="blocks" className="h-4 w-4"/>} onClick={()=>setCollectionOpen(true)}>New collection</Button>}</div>}/>
 <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{l:"Media records",v:summary.all,i:"image"},{l:"Images",v:summary.images,i:"image"},{l:"Documents",v:summary.documents,i:"file-text"},{l:"Trash",v:summary.trash,i:"trash"}].map(x=><Card key={x.l} className="p-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[var(--nx-brand-soft)] text-[var(--nx-brand-600)]"><Icon name={x.i} className="h-4 w-4"/></span><div><p className="text-xs text-[var(--nx-text-muted)]">{x.l}</p><p className="text-xl font-semibold text-[var(--nx-text)]">{x.v}</p></div></div></Card>)}</div>
 {canUpload&&filters.view!=="trash"&&<Card className="mb-5 p-5 sm:p-6">{!upload.storage_ready&&<div className="mb-4 rounded-xl border border-amber-300/50 bg-amber-50 px-4 py-3 text-sm text-amber-900 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-100"><strong>Media storage is not writable.</strong> Nexora cannot accept uploads until <code>storage/app/public</code> is writable by PHP.</div>}<div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_20rem]"><FilePicker label="Upload media" description={`Nexora inspects MIME type, checksum and image dimensions before storage. Maximum ${upload.max_mb} MB. Executable and active-content files are blocked.`} accept={upload.accepted} file={uploadForm.data.file} onChange={file=>uploadForm.setData("file",file)}/><div className="grid gap-3"><Select label="Folder" value={uploadForm.data.folder_id} onChange={value=>uploadForm.setData("folder_id",value)} options={[{value:"",label:"No folder"},...folders.map(item=>({value:String(item.id),label:item.name}))]}/><Input label="Title" value={uploadForm.data.title} onChange={e=>uploadForm.setData("title",e.target.value)} placeholder="Optional library title"/><Input label="Alt text" value={uploadForm.data.alt_text} onChange={e=>uploadForm.setData("alt_text",e.target.value)} placeholder="Describe meaningful images"/><Button loading={uploadForm.processing} disabled={!upload.storage_ready||!uploadForm.data.file} leadingIcon={<Icon name="plus" className="h-4 w-4"/>} onClick={()=>uploadForm.post("/admin/media/upload",{forceFormData:true,preserveScroll:true,onSuccess:()=>uploadForm.reset()})}>Upload to library</Button>{uploadForm.errors.file&&<p className="text-sm text-red-600">{uploadForm.errors.file}</p>}</div></div></Card>}
 <Card className="mb-5 p-4"><div className="grid gap-3 lg:grid-cols-[minmax(15rem,1fr)_13rem_13rem_auto_auto]"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search filename, title or alt text…" onKeyDown={e=>e.key==="Enter"&&apply()}/><Select ariaLabel="Media type" value={type} onChange={value=>{setType(value);apply({type:value})}} options={[{value:"",label:"All media types"},{value:"image",label:"Images"},{value:"video",label:"Video"},{value:"audio",label:"Audio"},{value:"document",label:"Documents"}]}/><Select ariaLabel="Media folder" value={folder} onChange={value=>{setFolder(value);apply({folder:value})}} options={folderOptions}/><Button variant="secondary" onClick={()=>apply()} leadingIcon={<Icon name="search" className="h-4 w-4"/>}>Search</Button><ButtonLink href={filters.view==="trash"?"/admin/media":"/admin/media?view=trash"} variant="secondary" leadingIcon={<Icon name={filters.view==="trash"?"image":"trash"} className="h-4 w-4"/>}>{filters.view==="trash"?"Library":"Trash"}</ButtonLink></div></Card>
 {assets.data.length===0?<Card className="p-10 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[var(--nx-brand-soft)] text-[var(--nx-brand-600)]"><Icon name="image" className="h-6 w-6"/></span><h2 className="mt-4 font-semibold text-[var(--nx-text)]">No media found</h2><p className="mt-2 text-sm text-[var(--nx-text-muted)]">Upload a supported asset or change the current filters.</p></Card>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{assets.data.map(asset=><Card key={asset.id} className="overflow-hidden"><div className="aspect-[4/3] border-b border-[var(--nx-border)]"><Preview asset={asset}/></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-[var(--nx-text)]">{asset.title}</p><p className="mt-1 truncate text-xs text-[var(--nx-text-muted)]">{asset.original_name}</p></div><Badge tone={asset.deleted_at?"danger":"neutral"}>{asset.deleted_at?"Trash":typeLabel(asset.media_type)}</Badge></div><div className="mt-3 flex flex-wrap gap-1.5"><Badge>{bytes(asset.size_bytes)}</Badge>{asset.width&&asset.height&&<Badge>{asset.width}×{asset.height}</Badge>}<Badge>{asset.usages_count} use{asset.usages_count===1?"":"s"}</Badge></div><div className="mt-4 flex items-center justify-end gap-1">{asset.url&&<IconButton label={`Open ${asset.title}`} onClick={()=>window.open(asset.url!,"_blank","noopener,noreferrer")}><Icon name="external" className="h-4 w-4"/></IconButton>}{!asset.deleted_at&&canManage&&<IconButton label={`Edit ${asset.title}`} onClick={()=>startEdit(asset)}><Icon name="edit" className="h-4 w-4"/></IconButton>}{!asset.deleted_at&&canDelete&&<IconButton label={`Move ${asset.title} to Trash`} tone="danger" onClick={()=>setDeleting(asset)}><Icon name="trash" className="h-4 w-4"/></IconButton>}{asset.deleted_at&&canDelete&&<IconButton label={`Restore ${asset.title}`} onClick={()=>router.post(`/admin/media/${asset.id}/restore`,{}, {preserveScroll:true})}><Icon name="rollback" className="h-4 w-4"/></IconButton>}{asset.deleted_at&&canForce&&asset.usages_count===0&&<IconButton label={`Permanently delete ${asset.title}`} tone="danger" onClick={()=>router.delete(`/admin/media/${asset.id}/force`,{preserveScroll:true})}><Icon name="trash" className="h-4 w-4"/></IconButton>}</div></div></Card>)}</div>}
 <div className="mt-5 flex items-center justify-between"><p className="text-sm text-[var(--nx-text-muted)]">{assets.total} media item{assets.total===1?"":"s"}</p><div className="flex gap-2">{assets.prev_page_url&&<ButtonLink href={assets.prev_page_url} variant="secondary" size="sm">Previous</ButtonLink>}{assets.next_page_url&&<ButtonLink href={assets.next_page_url} variant="secondary" size="sm">Next</ButtonLink>}</div></div>
 <Modal open={Boolean(editing)} onClose={()=>setEditing(null)} title="Media details" description="Update metadata without changing the immutable stored media payload." footer={<><Button variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button><Button loading={editForm.processing} onClick={saveEdit}>Save changes</Button></>}><div className="grid gap-4"><Input label="Title" value={editForm.data.title} onChange={e=>editForm.setData("title",e.target.value)}/><Input label="Alt text" value={editForm.data.alt_text} onChange={e=>editForm.setData("alt_text",e.target.value)} hint="Important for accessibility and image SEO."/><Textarea label="Caption" rows={3} value={editForm.data.caption} onChange={e=>editForm.setData("caption",e.target.value)}/><Textarea label="Description" rows={4} value={editForm.data.description} onChange={e=>editForm.setData("description",e.target.value)}/><Select label="Folder" value={editForm.data.folder_id} onChange={v=>editForm.setData("folder_id",v)} options={[{value:"",label:"No folder"},...folders.map(item=>({value:String(item.id),label:item.name}))]}/>{collections.length>0&&<div className="grid gap-2 sm:grid-cols-[1fr_auto]"><Select label="Add to collection" value={editForm.data.collection_id} onChange={v=>editForm.setData("collection_id",v)} options={[{value:"",label:"Choose collection"},...collections.map(item=>({value:String(item.id),label:item.name}))]}/><Button type="button" variant="secondary" className="sm:self-end" disabled={!editForm.data.collection_id} onClick={addCollection}>Add</Button></div>}</div></Modal>
 <Modal open={folderOpen} onClose={()=>setFolderOpen(false)} title="Create media folder" description="Folders organize the library without changing public URLs." footer={<><Button variant="secondary" onClick={()=>setFolderOpen(false)}>Cancel</Button><Button loading={folderForm.processing} onClick={()=>folderForm.post("/admin/media/folders",{preserveScroll:true,onSuccess:()=>{folderForm.reset();setFolderOpen(false)}})}>Create folder</Button></>}><div className="grid gap-4"><Input label="Folder name" value={folderForm.data.name} onChange={e=>folderForm.setData("name",e.target.value)}/><Select label="Parent folder" value={folderForm.data.parent_id} onChange={v=>folderForm.setData("parent_id",v)} options={[{value:"",label:"Top level"},...folders.map(item=>({value:String(item.id),label:item.name}))]}/></div></Modal>
 <Modal open={collectionOpen} onClose={()=>setCollectionOpen(false)} title="Create media collection" description="Collections group assets for campaigns, projects or editorial reuse." footer={<><Button variant="secondary" onClick={()=>setCollectionOpen(false)}>Cancel</Button><Button loading={collectionForm.processing} onClick={()=>collectionForm.post("/admin/media/collections",{preserveScroll:true,onSuccess:()=>{collectionForm.reset();setCollectionOpen(false)}})}>Create collection</Button></>}><div className="grid gap-4"><Input label="Collection name" value={collectionForm.data.name} onChange={e=>collectionForm.setData("name",e.target.value)}/><Textarea label="Description" rows={4} value={collectionForm.data.description} onChange={e=>collectionForm.setData("description",e.target.value)}/></div></Modal>
 <ConfirmDialog open={Boolean(deleting)} title="Move media to Trash?" description={deleting?`${deleting.title} will remain recoverable. Usage references are preserved.`:""} confirmLabel="Move to Trash" processing={false} onCancel={()=>setDeleting(null)} onConfirm={()=>deleting&&router.delete(`/admin/media/${deleting.id}`,{preserveScroll:true,onFinish:()=>setDeleting(null)})}/>
 </AdminLayout>;
}
