<?php

declare(strict_types=1);

$root=dirname(__DIR__);$write=null;$compare=null;foreach($argv as $arg){if(str_starts_with($arg,'--write='))$write=substr($arg,8);elseif(str_starts_with($arg,'--compare='))$compare=substr($arg,10);}if(($write===null&&$compare===null)||($write!==null&&$compare!==null)){fwrite(STDERR,"Usage: php scripts/database-data-plane-certify.php --write=<name.json> | --compare=<name.json>\n");exit(2);}if(!is_file($root.'/vendor/autoload.php')){fwrite(STDERR,"[Nexora DB Data Plane] FAIL — vendor/autoload.php missing.\n");exit(1);}require $root.'/vendor/autoload.php';$app=require $root.'/bootstrap/app.php';$kernel=$app->make(Illuminate\Contracts\Console\Kernel::class);$kernel->bootstrap();
try{
    $identity=$app->make(App\Nexora\Installation\Database\DatabaseDataPlaneIdentity::class);$current=$identity->current(true);$base=$root.'/storage/app/nexora/certification/database-profiles';if(!is_dir($base)&&!mkdir($base,0775,true)&&!is_dir($base))throw new RuntimeException('Unable to create database profile certification directory.');$name=$write??$compare;if(!is_string($name)||preg_match('/^[A-Za-z0-9._-]{1,120}\.json$/',$name)!==1)throw new RuntimeException('Database profile filename must be a safe .json basename.');$path=$base.'/'.$name;
    if($write!==null){file_put_contents($path,json_encode($current,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL);fwrite(STDOUT,"[Nexora DB Data Plane] BASELINE — driver={$current['driver']} data=".substr((string)$current['fingerprint'],0,16)." schema=".substr((string)$current['schema_fingerprint'],0,16)." tables=".(int)($current['schema_snapshot']['table_count']??0)."\n");exit(0);}
    if(!is_file($path))throw new RuntimeException('Database profile baseline missing ['.$name.'].');$baseline=json_decode((string)file_get_contents($path),true,2048,JSON_THROW_ON_ERROR);if(!is_array($baseline))throw new RuntimeException('Database profile baseline must decode to an object.');$errors=[];foreach(['driver','fingerprint','schema_fingerprint'] as $key)if(($baseline[$key]??null)!==($current[$key]??null))$errors[]="{$key} mismatch";if(($baseline['database_name_sha256']??null)!==($current['database_name_sha256']??null))$errors[]='logical database identity mismatch';if($errors!==[]){fwrite(STDERR,"[Nexora DB Data Plane] FAIL — ".implode('; ',$errors)."\nBaseline data/schema: ".($baseline['fingerprint']??'missing')." / ".($baseline['schema_fingerprint']??'missing')."\nCurrent data/schema: ".($current['fingerprint']??'missing')." / ".($current['schema_fingerprint']??'missing')."\n");exit(1);}fwrite(STDOUT,"[Nexora DB Data Plane] PASS — exact data-plane and structural schema match baseline [{$name}].\n");exit(0);
}catch(Throwable $e){fwrite(STDERR,"[Nexora DB Data Plane] FAIL — {$e->getMessage()}\n");exit(1);}finally{try{$kernel->terminate(new Symfony\Component\Console\Input\ArgvInput(),0);}catch(Throwable){}}
