<?php

declare(strict_types=1);
$root=dirname(__DIR__);require_once $root.'/scripts/lib/source-attestation.php';require_once $root.'/scripts/lib/n1-certification-session.php';require_once $root.'/app/Nexora/Foundation/Filesystem/AtomicFileWriter.php';
$operator='operator-name';$out='';foreach($argv as $arg){if(str_starts_with($arg,'--operator='))$operator=trim(substr($arg,11));elseif(str_starts_with($arg,'--out='))$out=trim(substr($arg,6));}
$platform=require $root.'/config/nexora.php';$version=(string)($platform['version']??'unknown');$source=nexoraComputeSourceAttestation($root);$config=require $root.'/config/nexora-browser-certification.php';
$session=nexoraEnsureCertificationSession($root);$sessionId=(string)$session['session_id'];
$runId=gmdate('Ymd-His').'-'.bin2hex(random_bytes(3));$dir=$out!==''?$out:$root.'/storage/app/nexora/n1-c5/operator-kit/'.$runId;$writer=new App\Nexora\Foundation\Filesystem\AtomicFileWriter();$writer->ensureDirectory($dir);
$matrix=[];foreach($config['browsers'] as $browser)foreach($config['viewports'] as $viewport)foreach($config['directions'] as $direction)foreach($config['themes'] as $theme)$matrix[]=['browser'=>$browser,'viewport'=>$viewport['name'],'width'=>$viewport['width'],'direction'=>$direction,'theme'=>$theme,'status'=>'fail'];
$checks=[];foreach($config['checks'] as $check)$checks[$check]='fail';
$browser=['schema'=>2,'platform_version'=>$version,'source_tree_sha256'=>$source['tree_sha256'],'certification_session_id'=>$sessionId,'base_url'=>'https://replace-target/','auditor'=>$operator,'completed_at'=>gmdate(DATE_ATOM),'environments'=>array_map(static fn($browser)=>['browser'=>$browser,'version'=>'','os'=>''],$config['browsers']),'matrix'=>$matrix,'assistive_technology'=>['name'=>'screen-reader-name','browser'=>'','os'=>'','status'=>'fail'],'checks'=>$checks,'notes'=>'All rows/checks start FAIL. Replace only after direct observation on the exact certified source.'];
$routes=[];foreach($config['web_vitals']['routes'] as $route)$routes[]=['path'=>$route,'browser'=>'','profile'=>'','runs'=>0,'lcp_ms'=>null,'inp_ms'=>null,'cls'=>null,'ttfb_ms'=>null,'status'=>'fail'];
$vitals=['schema'=>1,'platform_version'=>$version,'source_tree_sha256'=>$source['tree_sha256'],'certification_session_id'=>$sessionId,'base_url'=>'https://replace-target/','auditor'=>$operator,'completed_at'=>gmdate(DATE_ATOM),'thresholds'=>$config['web_vitals']['thresholds'],'routes'=>$routes,'notes'=>'Record median/representative observed metrics from at least the configured run count. Do not mark PASS from estimates.'];
$writer->write($dir.'/browser-evidence.json',json_encode($browser,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL,0755,0640);$writer->write($dir.'/web-vitals-evidence.json',json_encode($vitals,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL,0755,0640);
$standardsRoutes=implode(', ',(array)($config['standards']['routes']??[]));
$runbook="# Nexora N1.0-C5 Browser / Accessibility / W3C HTML+CSS / WAVE / Performance Runbook\n\nPlatform: `{$version}`  \nSource: `{$source['tree_sha256']}`  \nSession: `{$sessionId}`\n\n## Browser matrix\nRun Chrome, Edge and Firefox across 360/768/1440 widths, LTR/RTL, light/dark. Mark a row PASS only after checking layout, menus, tables, dialogs, forms and navigation without clipping or horizontal page overflow.\n\n## Accessibility\nKeyboard-only navigation, visible focus, skip link, modal focus trap, command palette keyboard behavior, labels with a real screen reader, reduced motion, 200% zoom and forced-colors must be observed. Record the actual assistive technology/browser/OS.\n\n## W3C HTML + CSS + WAVE standards gate\nRequired routes: {$standardsRoutes}. The C5 runner performs W3C Nu HTML validation, W3C CSS validation and WAVE evaluation on the real target. W3C HTML and CSS must each report zero errors. Warnings are recorded for review. WAVE must report zero Errors and zero Contrast Errors; every Alert must be manually reviewed before asserting `--wave-alerts-reviewed`. Shared WAVE API requires `WAVE_API_KEY`; never commit or paste the key into evidence. WAVE output is not an accessibility approval.\n\n## Web vitals\nCollect at least {$config['web_vitals']['minimum_runs_per_route']} runs per required route. Keep values within project ceilings: LCP {$config['web_vitals']['thresholds']['lcp_ms']}ms, INP {$config['web_vitals']['thresholds']['inp_ms']}ms, CLS {$config['web_vitals']['thresholds']['cls']}, TTFB {$config['web_vitals']['thresholds']['ttfb_ms']}ms.\n\n## Certify\nRun `scripts\\n1-c5-browser-performance-certify.bat --base-url=https://YOUR-TARGET --evidence={$dir} --auditor={$operator} --wave-alerts-reviewed`. For private targets use approved local/stand-alone validator endpoints via `--w3c-validator-url=`, `--w3c-css-validator-url=` and `--wave-api-url=`.\n";$writer->write($dir.'/RUNBOOK.md',$runbook,0755,0640);fwrite(STDOUT,"[N1.0-C5 Evidence Kit] Created {$dir}\n36 browser matrix rows + accessibility and web-vitals checks remain FAIL until observed; W3C HTML/CSS + WAVE remain live target gates.\n");
