<?php

declare(strict_types=1);
$root=dirname(__DIR__);require_once $root.'/bootstrap/nexora-process-environment.php';require_once $root.'/scripts/lib/source-attestation.php';require_once $root.'/scripts/lib/final-release-seal.php';require_once $root.'/scripts/lib/n1-certified-toolchain.php';$version=(string)((require $root.'/config/nexora.php')['version']??'unknown');$evidence='';$baseUrl='';$statusOnly=in_array('--status-only',$argv,true);foreach($argv as $arg){if(str_starts_with($arg,'--evidence='))$evidence=trim(substr($arg,11));elseif(str_starts_with($arg,'--base-url='))$baseUrl=trim(substr($arg,11));}$base=$root.'/storage/app/nexora/n1-c6';if($statusOnly){$p=$base.'/latest.json';if(is_file($p)){fwrite(STDOUT,(string)file_get_contents($p));exit(0);}fwrite(STDOUT,"[N1.0-C6] No prior C6 run evidence.\n");exit(2);}if($baseUrl==='')$baseUrl=trim((string)getenv('NEXORA_CERT_BASE_URL'));if($baseUrl===''){fwrite(STDERR,"[N1.0-C6] A real target URL is required: --base-url=https://target\n");exit(2);}
$runId=gmdate('Ymd-His').'-'.bin2hex(random_bytes(3));$dir=$base.'/'.$runId;$logs=$dir.'/steps';foreach([$base,$dir,$logs] as $d)if(!is_dir($d)&&!mkdir($d,0775,true)&&!is_dir($d))throw new RuntimeException("Unable to create {$d}");$source=nexoraComputeSourceAttestation($root);$env=NexoraBootstrapProcessEnvironment::build($root,$_ENV);$env['NEXORA_CERT_FINAL_EVIDENCE']='1';$env['NEXORA_CERT_BASE_URL']=$baseUrl;$steps=[];$status='pass';$first=null;$redact=static function(string $text):string{foreach(['/((?:password|passwd|secret|token|authorization|cookie|api[_-]?key)\s*[:=]\s*)([^\s\r\n]+)/i','/(Bearer\s+)[A-Za-z0-9._~+\/-]+/i'] as $p)$text=(string)preg_replace($p,'$1[REDACTED]',$text);return $text;};
$run=static function(string $id,string $label,array $cmd)use($root,$env,$logs,$redact,&$steps,&$status,&$first):bool{$line=implode(' ',array_map(static fn($v)=>escapeshellarg((string)$v),$cmd));fwrite(STDOUT,"\n[N1.0-C6] {$label}\n> {$line}\n");$started=microtime(true);$p=@proc_open($line,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$root,$env,['bypass_shell'=>false]);if(!is_resource($p)){$out='';$err='Unable to start process.';$code=127;}else{fclose($pipes[0]);$out=(string)stream_get_contents($pipes[1]);fclose($pipes[1]);$err=(string)stream_get_contents($pipes[2]);fclose($pipes[2]);$code=proc_close($p);}$out=$redact($out);$err=$redact($err);file_put_contents("{$logs}/{$id}.stdout.log",$out);file_put_contents("{$logs}/{$id}.stderr.log",$err);if($out!=='')fwrite(STDOUT,$out.(str_ends_with($out,"\n")?'':"\n"));if($err!=='')fwrite(STDERR,$err.(str_ends_with($err,"\n")?'':"\n"));$ok=$code===0;$steps[]=['id'=>$id,'label'=>$label,'status'=>$ok?'pass':'fail','required'=>true,'exit_code'=>$code,'duration_seconds'=>round(microtime(true)-$started,3),'stdout_log'=>"steps/{$id}.stdout.log",'stderr_log'=>"steps/{$id}.stderr.log"];if(!$ok){$status='blocked';if($first===null)$first=['id'=>$id,'label'=>$label,'exit_code'=>$code];}return $ok;};
$ordered=[
 ['c1-evidence','Exact-source C1 dependency/build PASS',[PHP_BINARY,'scripts/n1-c1-evidence-verify.php']],
 ['c2-evidence','Exact-source C2 Laravel/runtime/core-DB PASS',[PHP_BINARY,'scripts/n1-c2-evidence-verify.php']],
 ['c3-evidence','Exact-source C3 strict five-DB PASS',[PHP_BINARY,'scripts/n1-c3-database-matrix-evidence-verify.php']],
 ['c4-evidence','Exact-source C4 install/upgrade/restore PASS',[PHP_BINARY,'scripts/n1-c4-evidence-verify.php']],
 ['c5-evidence','Exact-source C5 browser/A11y/performance PASS',[PHP_BINARY,'scripts/n1-c5-evidence-verify.php']],
 ['ha-source','HA/final source contracts',[PHP_BINARY,'scripts/ha-final-contract-verify.php']],
 ['ha-readiness','Real target HA readiness',[PHP_BINARY,'artisan','nexora:ha:status']],
 ['ha-rehearsal','Real target scheduler/lease HA rehearsal',[PHP_BINARY,'artisan','nexora:ha:rehearse']],
];foreach($ordered as [$id,$label,$cmd]){if($status!=='pass')break;if(!$run($id,$label,$cmd))break;}
if($status==='pass'&&$evidence!=='')$run('ha-evidence','Import and validate real multi-node HA evidence',[PHP_BINARY,'scripts/n1-c6-ha-evidence-import.php','--input='.$evidence]);elseif($status==='pass')$run('ha-evidence','Validate existing real multi-node HA evidence',[PHP_BINARY,'scripts/ha-evidence-verify.php']);
if($status==='pass')$run('target-url-consistency','Require C5 and HA evidence from the same HTTPS target',[PHP_BINARY,'scripts/n1-c6-target-url-verify.php','--base-url='.$baseUrl]);
if($status==='pass')$run('target-evidence-intake','Seal all five operator evidence domains as one exact-source intake manifest',[PHP_BINARY,'scripts/target-evidence-intake.php','--input='.$root.'/storage/app/nexora/certification','--seal','--require-complete']);
if($status==='pass')$run('release-signing-readiness','Require operator release-signing key pair + active signer trust anchor',[PHP_BINARY,'scripts/release-signing-key.php']);
if($status==='pass')$run('release-trust-anchor','Verify active release signer identity trust anchor',[PHP_BINARY,'scripts/release-trust-anchor.php']);
if($status==='pass')$run('production-runtime-stage','Build verified Composer --no-dev production runtime stage',[PHP_BINARY,'scripts/production-dependency-stage.php','--build']);
if($status==='pass')$run('release-provenance','Prepare exact-source/session/toolchain/signer release provenance',[PHP_BINARY,'scripts/release-provenance.php']);
if($status==='pass')$run('final-target','Final exact-version automated certification + signed production packaging',[PHP_BINARY,'scripts/final-target-run.php','--final']);
if($status==='pass')$run('production-artifact','Independent signed production ZIP verification',[PHP_BINARY,'scripts/release-artifact-verify.php']);
if($status==='pass')$run('session-finalize','Finalize certification session against signed release artifacts',[PHP_BINARY,'scripts/n1-certification-session.php','--finalize']);
if($status==='pass')$run('closure-dashboard','Require all 11 closure domains and finalized signed production package PASS',[PHP_BINARY,'scripts/closure-dashboard.php']);
if($status==='pass')$run('c6-evidence','Seal final C6/N1.0 evidence manifest',[PHP_BINARY,'scripts/n1-c6-evidence-verify.php']);
$hash=static fn(string $f):?string=>is_file($f)?(hash_file('sha256',$f)?:null):null;$production=(function()use($root,$version){$fv=preg_replace('/[^0-9A-Za-z._-]+/','-',$version)?:'unknown';return $root.'/dist/nexora-'.$fv.'-production.zip';})();$summary=['schema'=>1,'chunk'=>'N1.0-C6','scope'=>'Multi-node HA + Final Release Closure','platform_version'=>$version,'source_tree_sha256'=>$source['tree_sha256'],'run_id'=>$runId,'status'=>$status,'first_blocker'=>$first,'base_url'=>$baseUrl,'artifacts'=>['c1_evidence_sha256'=>$hash($root.'/storage/app/nexora/n1-c1/latest.json'),'c2_evidence_sha256'=>$hash($root.'/storage/app/nexora/n1-c2/latest.json'),'c3_evidence_sha256'=>$hash($root.'/storage/app/nexora/certification/database-matrix.json'),'c4_evidence_sha256'=>$hash($root.'/storage/app/nexora/n1-c4/c4-evidence.json'),'c5_evidence_sha256'=>$hash($root.'/storage/app/nexora/n1-c5/c5-evidence.json'),'ha_evidence_sha256'=>$hash($root.'/storage/app/nexora/certification/ha-evidence.json'),'final_evidence_sha256'=>$hash($root.'/storage/app/nexora/certification/final-evidence.json'),'production_package_sha256'=>$hash($production),'release_seal_sha256'=>$hash(nexoraFinalReleaseSealPaths($root)['seal']),'release_signature_sha256'=>$hash(nexoraFinalReleaseSealPaths($root)['signature']),'release_public_key_sha256'=>$hash(nexoraFinalReleaseSealPaths($root)['public_key']),'release_trust_anchor_sha256'=>$hash($root.'/storage/app/nexora/release-signing/trust-anchor.json'),'dependency_sbom_sha256'=>$hash($root.'/storage/app/nexora/certification/dependency-sbom.json'),'production_dependencies_sha256'=>$hash($root.'/storage/app/nexora/certification/production-dependencies.json'),'release_provenance_sha256'=>$hash($root.'/storage/app/nexora/certification/release-provenance.json'),'certification_session_finalization_sha256'=>$hash(nexoraCertificationSessionFinalizationPath($root)),'certified_toolchain_sha256'=>$hash(nexoraCertifiedToolchainPath($root)),'certification_evidence_bundle_sha256'=>$hash(nexoraFinalReleaseSealPaths($root)['bundle']),'c6_evidence_sha256'=>$hash($root.'/storage/app/nexora/n1-c6/c6-evidence.json')],'steps'=>$steps,'finished_at'=>gmdate(DATE_ATOM)];$json=json_encode($summary,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;file_put_contents($dir.'/summary.json',$json);file_put_contents($base.'/latest.json',$json);$md="# Nexora N1.0-C6 Multi-node HA + Final Release Closure\n\nStatus: **".strtoupper($status)."**  \nPlatform: `{$version}`  \nSource: `{$source['tree_sha256']}`\n";if($first)$md.="First blocker: `{$first['id']}` — {$first['label']}\n";$md.="\n| Gate | Status | Exit |\n|---|---:|---:|\n";foreach($steps as $s)$md.='| '.$s['label'].' | '.strtoupper($s['status']).' | '.$s['exit_code']." |\n";file_put_contents($dir.'/summary.md',$md);file_put_contents($base.'/latest.md',$md);fwrite(STDOUT,"\n{$md}\nEvidence: storage/app/nexora/n1-c6/{$runId}/\n");exit($status==='pass'?0:1);
