<?php

declare(strict_types=1);$root=dirname(__DIR__);$errors=[];$read=static fn(string $p):string=>is_file($p)?(string)file_get_contents($p):'';
$session=$read($root.'/scripts/lib/n1-certification-session.php');foreach(['session_id','source_tree_sha256','composer_lock_sha256','package_lock_sha256','reviewed_locks_sha256','certified_toolchain_sha256','certification_session_max_age_hours','session-finalization.json','nexoraFinalizeCertificationSession'] as $m)if(!str_contains($session,$m))$errors[]="certification session contract missing [{$m}]";
$master=$read($root.'/scripts/n1-target-execution.php');foreach(['nexoraAcquireTargetExecutionLock','certification-session','n1-certification-session.php'] as $m)if(!str_contains($master,$m))$errors[]="target execution concurrency/session contract missing [{$m}]";
foreach(['n1-c4-evidence-prepare.php','n1-c5-evidence-prepare.php','n1-c6-evidence-prepare.php'] as $file){$text=$read($root.'/scripts/'.$file);if(!str_contains($text,'certification_session_id'))$errors[]="operator kit session binding missing [{$file}]";}
$seal=$read($root.'/scripts/lib/final-release-seal.php');foreach(['certification-evidence.zip','release-seal.json','release-seal.sig','release-public.pem','evidence-index.json','production','final_evidence_sha256','certified_toolchain_sha256','nexoraSignReleaseSeal'] as $m)if(!str_contains($seal,$m))$errors[]="final release seal contract missing [{$m}]";
$build=$read($root.'/scripts/build-production-release.php');if(!str_contains($build,'nexoraBuildFinalReleaseSeal'))$errors[]='production builder must create final release seal';
$closure=$read($root.'/scripts/lib/final-closure.php');if(!str_contains($closure,'signed production ZIP + certification evidence bundle + detached signature + release seal + finalized session'))$errors[]='final closure must describe signed/finalized production package';
$zero=$read($root.'/scripts/zero-state-verify.php');foreach(['storage/app/nexora/certification','storage/app/nexora/release-signing','dist'] as $m)if(!str_contains($zero,$m))$errors[]="strict zero-state missing release-evidence artifact boundary [{$m}]";
$config=$read($root.'/config/nexora-certification-evidence.php');foreach(['certification_session_max_age_hours','max_future_clock_skew_seconds'] as $m)if(!str_contains($config,$m))$errors[]="evidence clock/session policy missing [{$m}]";
if($errors!==[]){fwrite(STDERR,"[N1.0 Session/Release Seal Contracts] FAIL\n - ".implode("\n - ",$errors)."\n");exit(1);}fwrite(STDOUT,"[N1.0 Session/Release Seal Contracts] PASS\nSessions: 1 active exact-source/lock session\nMaster execution mutex: 1\nOperator session-bound domains: 3\nFinal evidence bundle: 1\nExternal release seal: 1\nDetached RSA signature: 1\nSession finalization receipt: 1\n");
