<?php

declare(strict_types=1);$root=dirname(__DIR__);require_once $root.'/scripts/lib/release-trust-anchor.php';
$register=in_array('--register',$argv,true);$revoke=in_array('--revoke',$argv,true);$export='';$confirm='';$keyId='';$reason='';foreach($argv as $arg){if(str_starts_with($arg,'--export='))$export=substr($arg,9);elseif(str_starts_with($arg,'--confirm='))$confirm=substr($arg,10);elseif(str_starts_with($arg,'--key-id='))$keyId=substr($arg,9);elseif(str_starts_with($arg,'--reason='))$reason=substr($arg,9);}try{
if($register){if($confirm!=='TRUST'){fwrite(STDERR,"[Nexora Release Trust Anchor] REFUSED — --confirm=TRUST required.\n");exit(2);}if($keyId===''){$cfg=nexoraReleaseSigningConfig($root);if(!is_file($cfg['public']))throw new RuntimeException('release public key missing');$info=nexoraReleasePublicKeyInfo((string)file_get_contents($cfg['public']));$keyId='nexora-'.substr($info['public_sha256'],0,16);} $a=nexoraRegisterReleaseTrustAnchor($root,$keyId);fwrite(STDOUT,"[Nexora Release Trust Anchor] ACTIVE {$a['key_id']} {$a['public_key_sha256']}\n");exit(0);}
if($revoke){if($confirm!=='REVOKE'){fwrite(STDERR,"[Nexora Release Trust Anchor] REFUSED — --confirm=REVOKE required.\n");exit(2);} $a=nexoraRevokeReleaseTrustAnchor($root,$reason);fwrite(STDOUT,"[Nexora Release Trust Anchor] REVOKED {$a['key_id']}\n");exit(0);}
$a=nexoraReleaseTrustAnchorRead($root);$errors=nexoraValidateReleaseTrustAnchor($root,$a);if($errors!==[]){fwrite(STDERR,"[Nexora Release Trust Anchor] FAIL\n - ".implode("\n - ",$errors)."\n");exit(1);}if($export!==''){$public=['schema'=>1,'status'=>'active','key_id'=>$a['key_id'],'public_key_sha256'=>$a['public_key_sha256'],'fingerprint'=>$a['fingerprint'],'registered_at'=>$a['registered_at']];$dir=dirname($export);if(!is_dir($dir)&&!mkdir($dir,0775,true)&&!is_dir($dir))throw new RuntimeException('unable to create export directory');file_put_contents($export,json_encode($public,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL);}
fwrite(STDOUT,"[Nexora Release Trust Anchor] PASS — key_id={$a['key_id']} public_sha256={$a['public_key_sha256']}\n");exit(0);
}catch(Throwable $e){fwrite(STDERR,"[Nexora Release Trust Anchor] FAIL — {$e->getMessage()}\n");exit(1);}
