import { router, useForm } from "@inertiajs/react";
import { AdminLayout } from "@admin/layout/AdminLayout";
import { PageHeader } from "@admin/components/PageHeader";
import { EmptyState } from "@admin/components/LoadingStates";
import { Icon } from "@admin/components/Icon";
import { Badge, Button, ButtonLink, Card, Checkbox, Input, TextLink } from "@nexora/admin-ui";

type Workflow={id:number;name:string;status:string;triggerKey:string;runCount:number;runsCount?:number|null;lastRunAt?:string|null;updatedAt?:string|null};
type Run={id:number;uuid:string;workflowName?:string|null;status:string;attempt:number;error?:string|null;createdAt?:string|null};
type Destination={id:number;name:string;url:string;enabled:boolean;timeoutSeconds:number;maxAttempts:number;lastDeliveredAt?:string|null};
type Endpoint={id:number;name:string;slug:string;url:string;enabled:boolean;lastReceivedAt?:string|null;rotatedAt?:string|null};
type Props={workflows:{data:Workflow[]};recentRuns:Run[];destinations:Destination[];endpoints:Endpoint[];newSecret?:{kind:string;name:string;secret:string}|null};

const when=(value?:string|null)=>value?new Date(value).toLocaleString():"Never";
const tone=(status:string):"success"|"warning"|"danger"|"neutral"=>status==="active"||status==="succeeded"||status==="delivered"?"success":status==="failed"?"danger":status==="paused"?"warning":"neutral";

export default function AutomationIndex({workflows,recentRuns,destinations,endpoints,newSecret}:Props){
 const destinationForm=useForm({name:"",url:"",timeoutSeconds:10,maxAttempts:5});
 const endpointForm=useForm({name:"",slug:""});
 const toggle=(url:string,enabled:boolean)=>router.patch(url,{enabled},{preserveScroll:true});
 return <AdminLayout>
  <PageHeader eyebrow="Automation" title="Workflows & Webhooks" description="Connect Nexora events to safe, observable actions. Conditions, retries, idempotency and signed webhook delivery are enforced by the workflow runtime." actions={<ButtonLink href="/admin/automation/create" leadingIcon={<Icon name="plus" className="h-4 w-4"/>}>New workflow</ButtonLink>}/>

  {newSecret&&<Card className="mt-5 border-[var(--nx-brand-300)] p-5"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[var(--nx-brand-soft)] text-[var(--nx-brand-600)]"><Icon name="key" className="h-4 w-4"/></span><div className="min-w-0"><p className="font-semibold text-[var(--nx-text)]">{newSecret.kind}</p><p className="mt-1 text-sm text-[var(--nx-text-muted)]">{newSecret.name} · Copy this secret now. Nexora will not display it again.</p><code className="mt-3 block overflow-x-auto rounded-xl border border-[var(--nx-border)] bg-[var(--nx-surface-subtle)] p-3 text-xs text-[var(--nx-text)]">{newSecret.secret}</code></div></div></Card>}

  <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
   <Metric icon="zap" label="Workflows" value={workflows.data.length} hint={`${workflows.data.filter(x=>x.status==="active").length} active`}/>
   <Metric icon="activity" label="Recent runs" value={recentRuns.length} hint={`${recentRuns.filter(x=>x.status==="failed").length} failed in recent history`}/>
   <Metric icon="send" label="Outbound destinations" value={destinations.length} hint={`${destinations.filter(x=>x.enabled).length} enabled`}/>
   <Metric icon="globe" label="Inbound endpoints" value={endpoints.length} hint={`${endpoints.filter(x=>x.enabled).length} enabled`}/>
  </div>

  <Card className="mt-5 overflow-hidden">
   <div className="flex flex-wrap items-start justify-between gap-3 border-b border-[var(--nx-border)] p-5"><div><h2 className="font-semibold text-[var(--nx-text)]">Workflow library</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">Triggers evaluate conditions before actions are queued. Paused workflows never receive new runs.</p></div><Badge tone="brand">Event driven</Badge></div>
   {workflows.data.length===0?<div className="p-5"><EmptyState title="No workflows yet" description="Create the first workflow from a Nexora event, condition set and one or more controlled actions." action={<ButtonLink href="/admin/automation/create">Create workflow</ButtonLink>}/></div>:<div className="divide-y divide-[var(--nx-border)]">{workflows.data.map(workflow=><div key={workflow.id} className="grid gap-3 p-5 lg:grid-cols-[minmax(0,1fr)_180px_140px_auto] lg:items-center"><div className="min-w-0"><TextLink href={`/admin/automation/${workflow.id}/edit`} tone="neutral">{workflow.name}</TextLink><p className="mt-1 text-xs text-[var(--nx-text-muted)]">Trigger: {workflow.triggerKey.replaceAll("."," · ")} · Updated {when(workflow.updatedAt)}</p></div><div><Badge tone={tone(workflow.status)}>{workflow.status}</Badge></div><div className="text-sm text-[var(--nx-text-muted)]">{workflow.runCount.toLocaleString()} runs</div><div className="flex flex-wrap gap-2 lg:justify-end"><ButtonLink size="sm" variant="secondary" href={`/admin/automation/${workflow.id}/edit`}>Edit</ButtonLink>{workflow.triggerKey==="manual"&&workflow.status==="active"&&<Button size="sm" variant="secondary" onClick={()=>router.post(`/admin/automation/${workflow.id}/run`,{}, {preserveScroll:true})}>Run now</Button>}<Button size="sm" variant="ghost" onClick={()=>router.patch(`/admin/automation/${workflow.id}/status`,{status:workflow.status==="active"?"paused":"active"},{preserveScroll:true})}>{workflow.status==="active"?"Pause":"Activate"}</Button></div></div>)}</div>}
  </Card>

  <div className="mt-5 grid gap-5 xl:grid-cols-2">
   <Card className="p-5"><div className="mb-4"><h2 className="font-semibold text-[var(--nx-text)]">Recent workflow runs</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">Execution attempts and failures remain observable instead of disappearing into background queues.</p></div>{recentRuns.length===0?<EmptyState title="No workflow runs" description="Runs will appear after an active trigger matches or a manual workflow is started."/>:<div className="divide-y divide-[var(--nx-border)]">{recentRuns.map(run=><div key={run.id} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><TextLink href={`/admin/automation/runs/${run.id}`} tone="neutral">{run.workflowName??"Deleted workflow"}</TextLink><p className="mt-0.5 text-xs text-[var(--nx-text-muted)]">{when(run.createdAt)} · Attempt {run.attempt}</p></div><Badge tone={tone(run.status)}>{run.status}</Badge></div>)}</div>}</Card>
   <Card className="p-5"><div className="mb-4"><h2 className="font-semibold text-[var(--nx-text)]">Runtime guarantees</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">N0.27 workflow safety is enforced server-side.</p></div><div className="grid gap-3 text-sm text-[var(--nx-text-muted)]"><Rule title="Idempotent webhook receipts" text="Duplicate inbound delivery keys are accepted once and ignored on replay."/><Rule title="Retry-safe workflow steps" text="Succeeded steps are not re-executed when a later step causes the job to retry."/><Rule title="Signed outbound delivery" text="HMAC SHA-256, timestamp and delivery identifiers are attached to every Nexora webhook."/><Rule title="Private-network protection" text="Production webhook delivery blocks private/reserved destinations and does not follow redirects."/></div></Card>
  </div>

  <div className="mt-5 grid gap-5 xl:grid-cols-2">
   <Card className="p-5"><div className="mb-5"><h2 className="font-semibold text-[var(--nx-text)]">Outbound webhook destinations</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">Create reusable signed destinations, then choose them from workflow actions.</p></div><form className="grid gap-4" onSubmit={e=>{e.preventDefault();destinationForm.post("/admin/automation/webhooks/destinations",{preserveScroll:true,onSuccess:()=>destinationForm.reset()});}}><Input label="Destination name" value={destinationForm.data.name} onChange={e=>destinationForm.setData("name",e.target.value)} error={destinationForm.errors.name}/><Input label="HTTPS endpoint URL" value={destinationForm.data.url} onChange={e=>destinationForm.setData("url",e.target.value)} placeholder="https://example.com/hooks/nexora" error={destinationForm.errors.url}/><div className="grid gap-4 sm:grid-cols-2"><Input label="Timeout seconds" type="number" min={2} max={30} value={destinationForm.data.timeoutSeconds} onChange={e=>destinationForm.setData("timeoutSeconds",Number(e.target.value))}/><Input label="Maximum attempts" type="number" min={1} max={8} value={destinationForm.data.maxAttempts} onChange={e=>destinationForm.setData("maxAttempts",Number(e.target.value))}/></div><div><Button type="submit" loading={destinationForm.processing} leadingIcon={<Icon name="plus" className="h-4 w-4"/>}>Add destination</Button></div></form><div className="mt-5 divide-y divide-[var(--nx-border)]">{destinations.map(item=><div key={item.id} className="flex items-start justify-between gap-3 py-3"><div className="min-w-0"><p className="font-medium text-[var(--nx-text)]">{item.name}</p><p className="mt-0.5 truncate text-xs text-[var(--nx-text-muted)]">{item.url}</p><p className="mt-1 text-xs text-[var(--nx-text-muted)]">Last delivered: {when(item.lastDeliveredAt)}</p></div><div className="flex items-center gap-2"><Button size="sm" variant="ghost" onClick={()=>router.post(`/admin/automation/webhooks/destinations/${item.id}/rotate`,{}, {preserveScroll:true})}>Rotate secret</Button><Checkbox checked={item.enabled} onChange={e=>toggle(`/admin/automation/webhooks/destinations/${item.id}`,e.target.checked)} label={item.enabled?"Enabled":"Disabled"}/></div></div>)}{destinations.length===0&&<p className="py-4 text-sm text-[var(--nx-text-muted)]">No outbound destinations configured.</p>}</div></Card>

   <Card className="p-5"><div className="mb-5"><h2 className="font-semibold text-[var(--nx-text)]">Inbound webhook endpoints</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">External systems sign JSON payloads using the endpoint secret. Verified receipts can trigger workflows.</p></div><form className="grid gap-4" onSubmit={e=>{e.preventDefault();endpointForm.post("/admin/automation/webhooks/endpoints",{preserveScroll:true,onSuccess:()=>endpointForm.reset()});}}><Input label="Endpoint name" value={endpointForm.data.name} onChange={e=>endpointForm.setData("name",e.target.value)} error={endpointForm.errors.name}/><Input label="Endpoint slug" value={endpointForm.data.slug} onChange={e=>endpointForm.setData("slug",e.target.value)} placeholder="crm-contact-created" hint="Optional. Nexora can generate a unique slug." error={endpointForm.errors.slug}/><div><Button type="submit" loading={endpointForm.processing} leadingIcon={<Icon name="plus" className="h-4 w-4"/>}>Create endpoint</Button></div></form><div className="mt-5 divide-y divide-[var(--nx-border)]">{endpoints.map(item=><div key={item.id} className="py-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-medium text-[var(--nx-text)]">{item.name}</p><p className="mt-0.5 truncate text-xs text-[var(--nx-text-muted)]">POST {item.url}</p><p className="mt-1 text-xs text-[var(--nx-text-muted)]">Last received: {when(item.lastReceivedAt)}</p></div><Checkbox checked={item.enabled} onChange={e=>toggle(`/admin/automation/webhooks/endpoints/${item.id}`,e.target.checked)} label={item.enabled?"Enabled":"Disabled"}/></div><div className="mt-2"><Button size="sm" variant="ghost" onClick={()=>router.post(`/admin/automation/webhooks/endpoints/${item.id}/rotate`,{}, {preserveScroll:true})}>Rotate secret</Button></div></div>)}{endpoints.length===0&&<p className="py-4 text-sm text-[var(--nx-text-muted)]">No inbound endpoints configured.</p>}</div></Card>
  </div>
 </AdminLayout>;
}
function Metric({icon,label,value,hint}:{icon:string;label:string;value:number;hint:string}){return <Card className="p-4"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[var(--nx-brand-soft)] text-[var(--nx-brand-600)]"><Icon name={icon} className="h-4 w-4"/></span><div><p className="text-xs font-medium text-[var(--nx-text-muted)]">{label}</p><p className="mt-0.5 text-xl font-semibold text-[var(--nx-text)]">{value.toLocaleString()}</p><p className="mt-1 text-xs text-[var(--nx-text-muted)]">{hint}</p></div></div></Card>}
function Rule({title,text}:{title:string;text:string}){return <div className="flex gap-3 rounded-xl border border-[var(--nx-border)] bg-[var(--nx-surface-subtle)] p-3"><Icon name="check" className="mt-0.5 h-4 w-4 shrink-0 text-[var(--nx-success)]"/><div><p className="font-medium text-[var(--nx-text)]">{title}</p><p className="mt-0.5 leading-5">{text}</p></div></div>}
