import { AdminLayout } from "@admin/layout/AdminLayout";
import { PageHeader } from "@admin/components/PageHeader";
import { Badge, ButtonLink, Card } from "@nexora/admin-ui";
type Step={id:number;key:string;type:string;status:string;attempt:number;input:unknown;output:unknown;error?:string|null;startedAt?:string|null;completedAt?:string|null};
type Delivery={id:number;uuid:string;destination?:string|null;url?:string|null;status:string;attempts:number;responseStatus?:number|null;error?:string|null;deliveredAt?:string|null};
type Props={run:{id:number;uuid:string;workflowName?:string|null;status:string;attempt:number;error?:string|null;context:unknown;output:unknown;event?:{key:string;uuid:string;payload:unknown}|null;steps:Step[];startedAt?:string|null;completedAt?:string|null};deliveries:Delivery[]};
const tone=(status:string):"success"|"warning"|"danger"|"neutral"=>["succeeded","delivered"].includes(status)?"success":status==="failed"?"danger":["running","queued","sending"].includes(status)?"warning":"neutral";
export default function AutomationRun({run,deliveries}:Props){return <AdminLayout><PageHeader eyebrow="Automation run" title={run.workflowName??"Workflow run"} description={`Run ${run.uuid}`} actions={<ButtonLink href="/admin/automation" variant="secondary">Back to workflows</ButtonLink>}/><div className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-[var(--nx-text)]">Execution steps</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">Attempt {run.attempt}. Completed steps are checkpointed for retry safety.</p></div><Badge tone={tone(run.status)}>{run.status}</Badge></div><div className="mt-4 divide-y divide-[var(--nx-border)]">{run.steps.map(step=><div key={step.id} className="py-4"><div className="flex items-center justify-between gap-3"><div><p className="font-medium text-[var(--nx-text)]">{step.key}</p><p className="mt-0.5 text-xs text-[var(--nx-text-muted)]">{step.type.replaceAll("."," · ")} · Attempt {step.attempt}</p></div><Badge tone={tone(step.status)}>{step.status}</Badge></div>{step.error&&<p className="mt-2 text-sm text-[var(--nx-danger)]">{step.error}</p>}</div>)}{run.steps.length===0&&<p className="py-4 text-sm text-[var(--nx-text-muted)]">The queued run has not started executing steps yet.</p>}</div></Card><Card className="p-5"><h2 className="font-semibold text-[var(--nx-text)]">Trigger context</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">Event: {run.event?.key??"manual"}</p><Json value={run.context}/>{run.error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/30 dark:text-red-300">{run.error}</p>}</Card></div><Card className="mt-5 p-5"><h2 className="font-semibold text-[var(--nx-text)]">Webhook deliveries</h2><p className="mt-1 text-sm text-[var(--nx-text-muted)]">Outbound delivery retries are independent from workflow execution retries.</p><div className="mt-4 divide-y divide-[var(--nx-border)]">{deliveries.map(item=><div key={item.id} className="flex items-start justify-between gap-3 py-3"><div className="min-w-0"><p className="font-medium text-[var(--nx-text)]">{item.destination??"Webhook destination"}</p><p className="mt-0.5 truncate text-xs text-[var(--nx-text-muted)]">{item.url}</p>{item.error&&<p className="mt-1 text-xs text-[var(--nx-danger)]">{item.error}</p>}</div><div className="text-right"><Badge tone={tone(item.status)}>{item.status}</Badge><p className="mt-1 text-xs text-[var(--nx-text-muted)]">{item.attempts} attempts{item.responseStatus?` · HTTP ${item.responseStatus}`:""}</p></div></div>)}{deliveries.length===0&&<p className="py-4 text-sm text-[var(--nx-text-muted)]">This workflow run has no webhook delivery actions.</p>}</div></Card></AdminLayout>}
function Json({value}:{value:unknown}){return <pre className="mt-4 max-h-80 overflow-auto rounded-xl border border-[var(--nx-border)] bg-[var(--nx-surface-subtle)] p-3 text-xs leading-5 text-[var(--nx-text)]">{JSON.stringify(value,null,2)}</pre>}
